//! Generates the Rust source files of the typed node API.
use std::collections::{BTreeMap, BTreeSet};

use heck::{ToSnakeCase, ToUpperCamelCase};
use proc_macro2::{Ident, Literal, Span, TokenStream};
use quote::{format_ident, quote};

use crate::metadata::{Input, Member, MemberKind, Node};

const HEADER: &str = "// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.\n";

/// An enum member type, shared by every node using the same name and values.
struct EnumType {
    name: String,
    values: Vec<String>,
    description: String,
    nodes: Vec<String>,
}

/// Rust type of a member, as stored in the generated struct.
enum FieldType<'a> {
    Float,
    Int,
    Bool,
    Enum(&'a EnumType),
    Input,
    Hybrid,
}

pub struct Generator<'a> {
    nodes: &'a [Node],
    enums: BTreeMap<String, EnumType>,
}

impl<'a> Generator<'a> {
    pub fn new(nodes: &'a [Node]) -> Self {
        let node_names = nodes
            .iter()
            .map(|node| node.name.as_str())
            .collect::<BTreeSet<_>>();
        let mut enums = BTreeMap::<String, EnumType>::new();

        for node in nodes {
            for member in &node.members {
                let MemberKind::Enum { values, .. } = &member.kind else {
                    continue;
                };
                if is_bool(values) {
                    continue;
                }

                let mut name = member.name.to_upper_camel_case();
                if node_names.contains(name.as_str()) {
                    name.push_str("Type");
                }

                let enum_type = enums.entry(name.clone()).or_insert_with(|| EnumType {
                    name,
                    values: values.clone(),
                    description: member.description.clone(),
                    nodes: Vec::new(),
                });
                assert_eq!(
                    &enum_type.values, values,
                    "enum {} has different values",
                    enum_type.name
                );
                enum_type.nodes.push(node.name.clone());
            }
        }

        Self { nodes, enums }
    }

    /// Returns the generated files, as (file name, content).
    pub fn files(&self) -> Vec<(String, String)> {
        let mut groups = BTreeMap::<String, Vec<&Node>>::new();
        for node in self.nodes {
            groups
                .entry(node.group.to_snake_case())
                .or_default()
                .push(node);
        }

        let mut files = vec![
            ("mod.rs".to_string(), render(self.module(&groups))),
            ("enums.rs".to_string(), render(self.enums_file())),
            ("ext.rs".to_string(), render(self.ext_file())),
            ("ops.rs".to_string(), self.ops_file()),
            ("tests.rs".to_string(), render(self.tests_file())),
        ];
        for (module, nodes) in &groups {
            let content = render(self.group_file(&nodes[0].group, nodes));
            files.push((format!("{module}.rs"), content));
        }

        files
    }

    fn module(&self, groups: &BTreeMap<String, Vec<&Node>>) -> TokenStream {
        let modules = groups
            .keys()
            .map(|module| format_ident!("{module}"))
            .collect::<Vec<_>>();

        quote! {
            #![doc = " Typed FastNoise2 nodes, generated from FastNoise2 metadata."]

            pub mod enums;
            pub mod ext;
            mod ops;
            #(pub mod #modules;)*

            pub use enums::*;
            pub use ext::*;
            #(pub use #modules::*;)*

            #[cfg(test)]
            mod tests;
        }
    }

    fn enums_file(&self) -> TokenStream {
        let enums = self.enums.values().map(|enum_type| {
            let name = format_ident!("{}", enum_type.name);
            let variants = enum_type
                .values
                .iter()
                .map(|value| format_ident!("{}", value.to_upper_camel_case()))
                .collect::<Vec<_>>();
            let values = &enum_type.values;

            let mut doc = doc_lines(&enum_type.description);
            if !doc.is_empty() {
                doc.push(String::new());
            }
            doc.push(format!(" Used by {}.", node_links(&enum_type.nodes)));

            quote! {
                #(#[doc = #doc])*
                #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
                pub enum #name {
                    #(#variants,)*
                }

                impl #name {
                    /// The FastNoise2 name of the value.
                    pub(crate) fn name(self) -> &'static str {
                        match self {
                            #(Self::#variants => #values,)*
                        }
                    }
                }
            }
        });

        quote! {
            #![doc = " Enum member types."]

            #(#enums)*
        }
    }

    /// Chaining methods: one per node with inputs, called on its first input.
    ///
    /// Inputs accepting only some node types get a marker trait implemented by those types,
    /// and the nodes whose first input is restricted get their own extension trait.
    fn ext_file(&self) -> TokenStream {
        let mut restricted = BTreeMap::<String, (&Member, &Vec<String>)>::new();
        for (member, input) in self.nodes.iter().flat_map(|node| node.inputs()) {
            if let Some(accepted) = &input.accepted {
                restricted
                    .entry(member.name.to_upper_camel_case())
                    .or_insert((member, accepted));
            }
        }

        let mut methods = BTreeMap::<Option<String>, Vec<TokenStream>>::new();
        for node in self.nodes {
            let inputs = node.inputs().collect::<Vec<_>>();
            let Some(((first, first_input), others)) = inputs.split_first() else {
                continue;
            };

            let name = format_ident!("{}", node.name);
            let method = format_ident!("{}", node.name.to_snake_case());
            let parameters = others
                .iter()
                .map(|(member, input)| {
                    let parameter = field_ident(member);
                    let bound = input_bound(input, member);
                    quote! { #parameter: impl #bound }
                })
                .collect::<Vec<_>>();
            let arguments = others.iter().map(|(member, _)| {
                let parameter = field_ident(member);
                quote! { #parameter.build() }
            });
            let doc = format!(
                " Creates a [`{}`] node with this generator as its `{}` input.",
                node.name, first.name
            );

            let trait_name = first_input
                .accepted
                .as_ref()
                .map(|_| format!("{}Ext", first.name.to_upper_camel_case()));
            methods.entry(trait_name).or_default().push(quote! {
                #[doc = #doc]
                fn #method(&self, #(#parameters),*) -> #name {
                    #name::new(self.build(), #(#arguments),*)
                }
            });
        }

        let marker_traits = restricted.iter().map(|(marker, (member, accepted))| {
            let marker = format_ident!("{marker}");
            let doc = format!(" Generators accepted by `{}` inputs.", member.name);
            let accepted = accepted.iter().map(|node| format_ident!("{node}"));
            quote! {
                #[doc = #doc]
                pub trait #marker: Generator {}

                #(impl #marker for #accepted {})*

                impl<G: #marker + ?Sized> #marker for &G {}
            }
        });

        let ext_traits = methods
            .iter()
            .map(|(trait_name, methods)| match trait_name {
                None => quote! {
                    /// Chaining methods available on every generator.
                    pub trait GeneratorExt: Generator {
                        #(#methods)*
                    }

                    impl<G: Generator + ?Sized> GeneratorExt for G {}
                },
                Some(trait_name) => {
                    let ext = format_ident!("{trait_name}");
                    let marker = format_ident!("{}", trait_name.trim_end_matches("Ext"));
                    let doc = format!(" Chaining methods available on [`{marker}`] generators.");
                    quote! {
                        #[doc = #doc]
                        pub trait #ext: #marker {
                            #(#methods)*
                        }

                        impl<G: #marker + ?Sized> #ext for G {}
                    }
                }
            });

        quote! {
            #![doc = " Chaining methods, creating a node from the generator used as its first input."]

            use super::*;
            use crate::node::Generator;

            #(#marker_traits)*
            #(#ext_traits)*
        }
    }

    /// Arithmetic operators on every generator, creating the matching operator nodes.
    ///
    /// Nodes whose `LHS` is an input (e.g. Add) are created from the left operand, and swap the
    /// operands when the constant is on the left. Nodes whose `LHS` is a hybrid (e.g. Subtract)
    /// set both sides.
    fn ops_file(&self) -> String {
        const OPERATORS: [(&str, &str, &str, bool); 5] = [
            ("Add", "add", "Add", true),
            ("Sub", "sub", "Subtract", false),
            ("Mul", "mul", "Multiply", true),
            ("Div", "div", "Divide", false),
            ("Rem", "rem", "Modulus", false),
        ];

        let impls = OPERATORS
            .iter()
            .map(|&(op_trait, op_method, node_name, commutative)| {
                let node = self
                    .nodes
                    .iter()
                    .find(|node| node.name == node_name)
                    .unwrap_or_else(|| panic!("missing {node_name} node"));
                let member = |name: &str| {
                    node.members
                        .iter()
                        .find(|member| member.name == name)
                        .unwrap_or_else(|| panic!("missing {name} member of {node_name}"))
                };
                let (lhs, rhs) = (member("LHS"), member("RHS"));

                let op_trait = format_ident!("{op_trait}");
                let op_method = format_ident!("{op_method}");
                let output = format_ident!("{node_name}");
                let with_rhs = format_ident!("with_{}", rhs.name.to_snake_case());

                // (generator on the left, constant on the left)
                let (generator_lhs, constant_lhs) = match lhs.kind {
                    MemberKind::Input(_) => {
                        assert!(commutative, "{node_name} needs its LHS input on the left");
                        (
                            quote! { #output::new(self.build()).#with_rhs(rhs) },
                            quote! { #output::new(rhs.build()).#with_rhs(self) },
                        )
                    }
                    _ => {
                        let constructor = format_ident!("{}", node_name.to_snake_case());
                        let with_lhs = format_ident!("with_{}", lhs.name.to_snake_case());
                        let body = quote! { #constructor().#with_lhs(self).#with_rhs(rhs) };
                        (body.clone(), body)
                    }
                };

                quote! {
                    impl<R: Into<Hybrid>> ops::#op_trait<R> for __Generator {
                        type Output = #output;

                        fn #op_method(self, rhs: R) -> #output {
                            #generator_lhs
                        }
                    }

                    impl<R: Into<Hybrid>> ops::#op_trait<R> for &__Generator {
                        type Output = #output;

                        fn #op_method(self, rhs: R) -> #output {
                            #generator_lhs
                        }
                    }

                    impl ops::#op_trait<__Generator> for f32 {
                        type Output = #output;

                        fn #op_method(self, rhs: __Generator) -> #output {
                            #constant_lhs
                        }
                    }

                    impl ops::#op_trait<&__Generator> for f32 {
                        type Output = #output;

                        fn #op_method(self, rhs: &__Generator) -> #output {
                            #constant_lhs
                        }
                    }
                }
            });

        let generators = self.nodes.iter().map(|node| format_ident!("{}", node.name));

        let impls = render_items(quote! {
            #(#impls)*

            /// Negation, multiplying by -1.
            impl ops::Neg for __Generator {
                type Output = Multiply;

                fn neg(self) -> Multiply {
                    self * -1.0
                }
            }

            /// Negation, multiplying by -1.
            impl ops::Neg for &__Generator {
                type Output = Multiply;

                fn neg(self) -> Multiply {
                    self * -1.0
                }
            }
        });
        let macro_body = impls
            .replace("__Generator", "$generator")
            .lines()
            .map(|line| match line {
                "" => String::new(),
                line => format!("        {line}"),
            })
            .collect::<Vec<_>>()
            .join("\n");

        let uses = render_items(quote! {
            #![doc = " Arithmetic operators on generators, with constants on either side."]

            use std::ops;

            use super::*;
            use crate::node::{Generator, Hybrid, Node};
        });
        let invocation = render_items(quote! {
            operators!(Node, #(#generators),*);
        });

        format!(
            "{HEADER}{uses}\nmacro_rules! operators {{\n    ($($generator:ty),*) => {{$(\n{macro_body}\n    )*}};\n}}\n\n{invocation}"
        )
    }

    /// Tests comparing every typed node and builder method with the same node built by name.
    ///
    /// Each builder test sets one member to a non default value, on the typed node and on a
    /// [`NodeBuilder`] with every other member at its default, and checks both outputs match.
    fn tests_file(&self) -> TokenStream {
        let tests = self.nodes.iter().flat_map(|node| {
            let default_test = format_ident!("{}_default", node.name.to_snake_case());
            let typed = self.typed_node(node);
            let manual = self.manual_node(node, None);
            let default = quote! {
                #[test]
                fn #default_test() {
                    assert_same(#typed, #manual);
                }
            };

            let member_tests = node
                .members
                .iter()
                .filter(|member| !matches!(member.kind, MemberKind::Input(_)))
                .map(move |member| {
                    let test = format_ident!(
                        "{}_{}",
                        node.name.to_snake_case(),
                        member.name.to_snake_case()
                    );
                    let method = format_ident!("with_{}", member.name.to_snake_case());
                    let (typed_value, member_value) = self.test_value(member);
                    let typed = self.typed_node(node);
                    let manual = self.manual_node(node, Some((member, member_value)));
                    quote! {
                        #[test]
                        fn #test() {
                            assert_same(#typed.#method(#typed_value), #manual);
                        }
                    }
                });

            std::iter::once(default).chain(member_tests)
        });

        quote! {
            #![doc = " Tests comparing typed nodes with nodes built by name."]

            use super::*;
            use crate::node::{Generator, MemberValue, Node, NodeBuilder};

            fn source() -> Node {
                perlin().build()
            }

            fn domain_warp() -> DomainWarpGradient {
                perlin().domain_warp_gradient()
            }

            fn hybrid() -> Node {
                sine_wave().build()
            }

            fn assert_same(typed: impl Generator, manual: NodeBuilder) {
                let grid = |node: &Node| {
                    let mut output = vec![0.0; 64];
                    node.gen_uniform_grid_2d(&mut output, -40.0, -40.0, 8, 8, 10.0, 10.0, 1337);
                    output
                };
                let typed = grid(&typed.build());
                let manual = grid(&manual.build().unwrap());
                let same = typed
                    .iter()
                    .zip(&manual)
                    .all(|(typed, manual)| typed == manual || (typed.is_nan() && manual.is_nan()));
                assert!(same, "typed {typed:?} != manual {manual:?}");
            }

            #(#tests)*
        }
    }

    /// Typed node with every member at its default, inputs from the test helpers.
    fn typed_node(&self, node: &Node) -> TokenStream {
        let inputs = node.inputs().collect::<Vec<_>>();
        let Some(((_, first_input), others)) = inputs.split_first() else {
            let function = format_ident!("{}", node.name.to_snake_case());
            return quote! { #function() };
        };

        let method = format_ident!("{}", node.name.to_snake_case());
        let receiver = test_input(first_input);
        let arguments = others.iter().map(|(_, input)| test_input(input));
        quote! { #receiver.#method(#(#arguments),*) }
    }

    /// The same node built by name, every member set to its default, `changed` set last.
    fn manual_node(&self, node: &Node, changed: Option<(&Member, TokenStream)>) -> TokenStream {
        let node_name = &node.name;
        let sets = node.members.iter().map(|member| {
            let member_name = &member.name;
            let value = match &member.kind {
                MemberKind::Input(input) => test_input(input),
                _ => self.member_value(member),
            };
            quote! { .set(#member_name, #value).unwrap() }
        });
        let changed = changed.map(|(member, value)| {
            let member_name = &member.name;
            quote! { .set(#member_name, #value).unwrap() }
        });

        quote! {
            NodeBuilder::new(#node_name).unwrap()
                #(#sets)*
                #changed
        }
    }

    /// `MemberValue` of the default value of a member.
    fn member_value(&self, member: &Member) -> TokenStream {
        match (&member.kind, self.field_type(member)) {
            (MemberKind::Float { default } | MemberKind::Hybrid { default }, _) => {
                let default = float_literal(*default);
                quote! { MemberValue::Float(#default) }
            }
            (MemberKind::Int { default }, _) => {
                let default = int_literal(*default);
                quote! { MemberValue::Int(#default) }
            }
            (MemberKind::Enum { default, .. }, FieldType::Bool) => {
                let value = if *default == 1 { "True" } else { "False" };
                quote! { MemberValue::from(#value) }
            }
            (MemberKind::Enum { values, default }, _) => {
                let value = &values[*default];
                quote! { MemberValue::from(#value) }
            }
            (MemberKind::Input(_), _) => unreachable!("inputs are set from the test helpers"),
        }
    }

    /// A non default test value, as (typed builder argument, `MemberValue`).
    fn test_value(&self, member: &Member) -> (TokenStream, TokenStream) {
        match (&member.kind, self.field_type(member)) {
            (MemberKind::Float { default }, _) => {
                let value = float_literal(default + 1.5);
                (quote! { #value }, quote! { MemberValue::Float(#value) })
            }
            (MemberKind::Int { default }, _) => {
                let value = int_literal(default + 1);
                (quote! { #value }, quote! { MemberValue::Int(#value) })
            }
            (MemberKind::Enum { default, .. }, FieldType::Bool) => {
                let value = *default != 1;
                let name = if value { "True" } else { "False" };
                (quote! { #value }, quote! { MemberValue::from(#name) })
            }
            (MemberKind::Enum { values, default }, FieldType::Enum(enum_type)) => {
                let value = &values[(default + 1) % values.len()];
                let enum_name = format_ident!("{}", enum_type.name);
                let variant = format_ident!("{}", value.to_upper_camel_case());
                (
                    quote! { #enum_name::#variant },
                    quote! { MemberValue::from(#value) },
                )
            }
            (MemberKind::Hybrid { .. }, _) => {
                (quote! { hybrid() }, quote! { MemberValue::from(hybrid()) })
            }
            _ => unreachable!("inputs have no test value"),
        }
    }

    fn group_file(&self, group: &str, nodes: &[&Node]) -> TokenStream {
        let module_doc = format!(" {group} nodes.");

        let enum_names = nodes
            .iter()
            .flat_map(|node| &node.members)
            .filter_map(|member| match self.field_type(member) {
                FieldType::Enum(enum_type) => Some(enum_type.name.as_str()),
                _ => None,
            })
            .collect::<BTreeSet<_>>()
            .into_iter()
            .map(|name| format_ident!("{name}"))
            .collect::<Vec<_>>();
        let enum_import = (!enum_names.is_empty()).then(|| {
            quote! { use super::enums::{#(#enum_names),*}; }
        });

        let has_hybrid = nodes
            .iter()
            .flat_map(|node| &node.members)
            .any(|member| matches!(member.kind, MemberKind::Hybrid { .. }));
        let core_import = if has_hybrid {
            quote! { use crate::node::{Generator, Hybrid, Node, NodeBuilder}; }
        } else {
            quote! { use crate::node::{Generator, Node, NodeBuilder}; }
        };

        let nodes = nodes.iter().map(|node| self.node(node));

        quote! {
            #![doc = #module_doc]

            #enum_import
            #core_import

            #(#nodes)*
        }
    }

    fn node(&self, node: &Node) -> TokenStream {
        let name = format_ident!("{}", node.name);
        let node_name = &node.name;
        let doc = if node.description.is_empty() {
            vec![format!(" {} node.", node.name)]
        } else {
            doc_lines(&node.description)
        };

        let fields = node.members.iter().map(|member| {
            let field = field_ident(member);
            let rust_type = self.rust_type(member);
            quote! { #field: #rust_type }
        });

        // Every member set to its default value, inputs set from the constructor parameters
        let initializers = node
            .members
            .iter()
            .map(|member| {
                let field = field_ident(member);
                match self.default_value(member) {
                    Some(default) => quote! { #field: #default },
                    None => quote! { #field },
                }
            })
            .collect::<Vec<_>>();

        let inputs = node
            .inputs()
            .map(|(member, _)| field_ident(member))
            .collect::<Vec<_>>();
        let (default, constructor) = if inputs.is_empty() {
            let function = format_ident!("{}", node.name.to_snake_case());
            let function_doc =
                format!(" Creates a [`{}`] node with its default values.", node.name);
            let default = quote! {
                impl Default for #name {
                    fn default() -> Self {
                        Self { #(#initializers,)* }
                    }
                }

                #[doc = #function_doc]
                pub fn #function() -> #name {
                    #name::default()
                }
            };
            (Some(default), None)
        } else {
            let constructor = quote! {
                pub(crate) fn new(#(#inputs: Node),*) -> Self {
                    Self { #(#initializers,)* }
                }
            };
            (None, Some(constructor))
        };

        let builders = node
            .members
            .iter()
            .filter(|member| !matches!(member.kind, MemberKind::Input(_)))
            .map(|member| self.builder(member));

        let sets = node.members.iter().map(|member| {
            let member_name = &member.name;
            let field = field_ident(member);
            let value = match self.field_type(member) {
                FieldType::Float | FieldType::Int => quote! { self.#field },
                FieldType::Bool => quote! { if self.#field { "True" } else { "False" } },
                FieldType::Enum(_) => quote! { self.#field.name() },
                FieldType::Input | FieldType::Hybrid => quote! { &self.#field },
            };
            quote! { .and_then(|builder| builder.set(#member_name, #value)) }
        });

        quote! {
            #(#[doc = #doc])*
            #[derive(Clone, Debug)]
            pub struct #name {
                #(#fields,)*
            }

            #default

            impl #name {
                #constructor
                #(#builders)*
            }

            impl Generator for #name {
                fn build(&self) -> Node {
                    NodeBuilder::new(#node_name)
                        #(#sets)*
                        .and_then(NodeBuilder::build)
                        .expect("generated from FastNoise2 metadata")
                }
            }
        }
    }

    fn builder(&self, member: &Member) -> TokenStream {
        let field = field_ident(member);
        let parameter = format_ident!("{}", member.name.to_snake_case());
        let method = format_ident!("with_{}", member.name.to_snake_case());

        let mut doc = doc_lines(&member.description);
        if !doc.is_empty() {
            doc.push(String::new());
        }
        doc.push(format!(" Default: `{}`", self.default_doc(member)));

        match self.field_type(member) {
            FieldType::Hybrid => quote! {
                #(#[doc = #doc])*
                pub fn #method(mut self, #parameter: impl Into<Hybrid>) -> Self {
                    self.#field = #parameter.into();
                    self
                }
            },
            _ => {
                let rust_type = self.rust_type(member);
                quote! {
                    #(#[doc = #doc])*
                    pub fn #method(mut self, #parameter: #rust_type) -> Self {
                        self.#field = #parameter;
                        self
                    }
                }
            }
        }
    }

    fn field_type(&self, member: &Member) -> FieldType<'_> {
        match &member.kind {
            MemberKind::Float { .. } => FieldType::Float,
            MemberKind::Int { .. } => FieldType::Int,
            MemberKind::Enum { values, .. } if is_bool(values) => FieldType::Bool,
            MemberKind::Enum { values, .. } => FieldType::Enum(
                self.enums
                    .values()
                    .find(|enum_type| &enum_type.values == values)
                    .expect("enum type collected"),
            ),
            MemberKind::Input(_) => FieldType::Input,
            MemberKind::Hybrid { .. } => FieldType::Hybrid,
        }
    }

    fn rust_type(&self, member: &Member) -> TokenStream {
        match self.field_type(member) {
            FieldType::Float => quote! { f32 },
            FieldType::Int => quote! { i32 },
            FieldType::Bool => quote! { bool },
            FieldType::Enum(enum_type) => {
                let name = format_ident!("{}", enum_type.name);
                quote! { #name }
            }
            FieldType::Input => quote! { Node },
            FieldType::Hybrid => quote! { Hybrid },
        }
    }

    /// Rust expression of the default value, `None` for inputs.
    fn default_value(&self, member: &Member) -> Option<TokenStream> {
        Some(match (&member.kind, self.field_type(member)) {
            (MemberKind::Float { default }, _) => float_literal(*default),
            (MemberKind::Int { default }, _) => int_literal(*default),
            (MemberKind::Enum { default, .. }, FieldType::Bool) => {
                let default = *default == 1;
                quote! { #default }
            }
            (MemberKind::Enum { values, default }, FieldType::Enum(enum_type)) => {
                let name = format_ident!("{}", enum_type.name);
                let variant = format_ident!("{}", values[*default].to_upper_camel_case());
                quote! { #name::#variant }
            }
            (MemberKind::Hybrid { default }, _) => {
                let default = float_literal(*default);
                quote! { Hybrid::Value(#default) }
            }
            _ => return None,
        })
    }

    fn default_doc(&self, member: &Member) -> String {
        match (&member.kind, self.field_type(member)) {
            (MemberKind::Float { default } | MemberKind::Hybrid { default }, _) => {
                format!("{default:?}")
            }
            (MemberKind::Int { default }, _) => default.to_string(),
            (MemberKind::Enum { default, .. }, FieldType::Bool) => (*default == 1).to_string(),
            (MemberKind::Enum { values, default }, FieldType::Enum(enum_type)) => {
                format!(
                    "{}::{}",
                    enum_type.name,
                    values[*default].to_upper_camel_case()
                )
            }
            _ => unreachable!("inputs have no default"),
        }
    }
}

/// Formats generated tokens as a Rust source file.
fn render(tokens: TokenStream) -> String {
    format!("{HEADER}{}", render_items(tokens))
}

/// Formats generated items, with blank lines between them.
fn render_items(tokens: TokenStream) -> String {
    let file = syn::parse2(tokens).expect("generated code is valid Rust");
    space_items(&prettyplease::unparse(&file))
}

/// Adds a blank line between items, which `prettyplease` puts on consecutive lines.
fn space_items(code: &str) -> String {
    let mut out = String::new();
    let mut previous = "";

    for line in code.lines() {
        let current = line.trim_start();
        let ends_item = previous == "}" || previous.ends_with(';') || previous.ends_with("{}");
        let starts_item = ["///", "#[", "pub ", "pub(", "fn ", "impl ", "impl<", "use "]
            .iter()
            .any(|start| current.starts_with(start));
        let is_use_group = previous.starts_with("use ") && current.starts_with("use ");
        let is_impl_group = previous.ends_with("{}") && current.ends_with("{}");
        let after_module_doc = previous.starts_with("//!") && !current.starts_with("//!");

        if (ends_item && starts_item && !is_use_group && !is_impl_group) || after_module_doc {
            out.push('\n');
        }
        out.push_str(line);
        out.push('\n');
        previous = current;
    }

    out
}

/// Float literal without suffix, always with a decimal point (e.g. `2.0`).
fn float_literal(value: f32) -> TokenStream {
    let literal = Literal::f32_unsuffixed(value.abs());
    if value < 0.0 {
        quote! { -#literal }
    } else {
        quote! { #literal }
    }
}

/// Integer literal without suffix.
fn int_literal(value: i32) -> TokenStream {
    let literal = Literal::u32_unsuffixed(value.unsigned_abs());
    if value < 0 {
        quote! { -#literal }
    } else {
        quote! { #literal }
    }
}

/// Field identifier of a member, escaped if it is a Rust keyword.
fn field_ident(member: &Member) -> Ident {
    let name = member.name.to_snake_case();
    if syn::parse_str::<Ident>(&name).is_ok() {
        Ident::new(&name, Span::call_site())
    } else {
        Ident::new_raw(&name, Span::call_site())
    }
}

/// Test helper providing a node for an input.
fn test_input(input: &Input) -> TokenStream {
    match input.accepted {
        Some(_) => quote! { domain_warp() },
        None => quote! { source() },
    }
}

/// Trait bound of an input parameter: any generator, or the marker trait of the accepted nodes.
fn input_bound(input: &Input, member: &Member) -> TokenStream {
    match input.accepted {
        Some(_) => {
            let marker = format_ident!("{}", member.name.to_upper_camel_case());
            quote! { #marker }
        }
        None => quote! { Generator },
    }
}

fn is_bool(values: &[String]) -> bool {
    values == ["False", "True"]
}

/// Doc comment lines, with a leading space and bare URLs turned into links.
fn doc_lines(text: &str) -> Vec<String> {
    text.lines()
        .map(|line| {
            let line = line
                .split(' ')
                .map(|word| {
                    if word.starts_with("http://") || word.starts_with("https://") {
                        format!("<{word}>")
                    } else {
                        word.to_string()
                    }
                })
                .collect::<Vec<_>>()
                .join(" ");
            format!(" {}", line.trim_end())
        })
        .collect()
}

fn node_links(nodes: &[String]) -> String {
    nodes
        .iter()
        .map(|node| format!("[`{node}`](super::{node})"))
        .collect::<Vec<_>>()
        .join(", ")
}
