//! Generates the Rust source files of the typed node API.
use std::collections::{BTreeMap, BTreeSet};

use heck::{ToSnakeCase, ToUpperCamelCase};
use proc_macro2::{Ident, Literal, Span, TokenStream};
use quote::{format_ident, quote};

use crate::metadata::{Member, MemberKind, Node};

const HEADER: &str = "// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.\n";

/// An enum member type, shared by every node using the same name and values.
struct EnumType {
    name: String,
    values: Vec<String>,
    description: String,
    nodes: Vec<String>,
}

/// Rust type of a member, as stored in the generated struct.
enum FieldType<'a> {
    Float,
    Int,
    Bool,
    Enum(&'a EnumType),
    Input,
    Hybrid,
}

pub struct Generator<'a> {
    nodes: &'a [Node],
    enums: BTreeMap<String, EnumType>,
}

impl<'a> Generator<'a> {
    pub fn new(nodes: &'a [Node]) -> Self {
        let node_names = nodes
            .iter()
            .map(|node| node.name.as_str())
            .collect::<BTreeSet<_>>();
        let mut enums = BTreeMap::<String, EnumType>::new();

        for node in nodes {
            for member in &node.members {
                let MemberKind::Enum { values, .. } = &member.kind else {
                    continue;
                };
                if is_bool(values) {
                    continue;
                }

                let mut name = member.name.to_upper_camel_case();
                if node_names.contains(name.as_str()) {
                    name.push_str("Type");
                }

                let enum_type = enums.entry(name.clone()).or_insert_with(|| EnumType {
                    name,
                    values: values.clone(),
                    description: member.description.clone(),
                    nodes: Vec::new(),
                });
                assert_eq!(
                    &enum_type.values, values,
                    "enum {} has different values",
                    enum_type.name
                );
                enum_type.nodes.push(node.name.clone());
            }
        }

        Self { nodes, enums }
    }

    /// Returns the generated files, as (file name, content).
    pub fn files(&self) -> Vec<(String, String)> {
        let mut groups = BTreeMap::<String, Vec<&Node>>::new();
        for node in self.nodes {
            groups
                .entry(node.group.to_snake_case())
                .or_default()
                .push(node);
        }

        let mut files = vec![
            ("mod.rs".to_string(), render(self.module(&groups))),
            ("enums.rs".to_string(), render(self.enums_file())),
        ];
        for (module, nodes) in &groups {
            let content = render(self.group_file(&nodes[0].group, nodes));
            files.push((format!("{module}.rs"), content));
        }

        files
    }

    fn module(&self, groups: &BTreeMap<String, Vec<&Node>>) -> TokenStream {
        let modules = groups
            .keys()
            .map(|module| format_ident!("{module}"))
            .collect::<Vec<_>>();

        quote! {
            #![doc = " Typed FastNoise2 nodes, generated from FastNoise2 metadata."]

            pub mod enums;
            #(pub mod #modules;)*

            pub use enums::*;
            #(pub use #modules::*;)*
        }
    }

    fn enums_file(&self) -> TokenStream {
        let enums = self.enums.values().map(|enum_type| {
            let name = format_ident!("{}", enum_type.name);
            let variants = enum_type
                .values
                .iter()
                .map(|value| format_ident!("{}", value.to_upper_camel_case()))
                .collect::<Vec<_>>();
            let values = &enum_type.values;

            let mut doc = doc_lines(&enum_type.description);
            if !doc.is_empty() {
                doc.push(String::new());
            }
            doc.push(format!(" Used by {}.", node_links(&enum_type.nodes)));

            quote! {
                #(#[doc = #doc])*
                #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
                pub enum #name {
                    #(#variants,)*
                }

                impl #name {
                    /// The FastNoise2 name of the value.
                    pub(crate) fn name(self) -> &'static str {
                        match self {
                            #(Self::#variants => #values,)*
                        }
                    }
                }
            }
        });

        quote! {
            #![doc = " Enum member types."]

            #(#enums)*
        }
    }

    fn group_file(&self, group: &str, nodes: &[&Node]) -> TokenStream {
        let module_doc = format!(" {group} nodes.");

        let enum_names = nodes
            .iter()
            .flat_map(|node| &node.members)
            .filter_map(|member| match self.field_type(member) {
                FieldType::Enum(enum_type) => Some(enum_type.name.as_str()),
                _ => None,
            })
            .collect::<BTreeSet<_>>()
            .into_iter()
            .map(|name| format_ident!("{name}"))
            .collect::<Vec<_>>();
        let enum_import = (!enum_names.is_empty()).then(|| {
            quote! { use super::enums::{#(#enum_names),*}; }
        });

        let has_hybrid = nodes
            .iter()
            .flat_map(|node| &node.members)
            .any(|member| matches!(member.kind, MemberKind::Hybrid { .. }));
        let core_import = if has_hybrid {
            quote! { use crate::node::{Generator, Hybrid, Node, NodeBuilder}; }
        } else {
            quote! { use crate::node::{Generator, Node, NodeBuilder}; }
        };

        let nodes = nodes.iter().map(|node| self.node(node));

        quote! {
            #![doc = #module_doc]

            #enum_import
            #core_import

            #(#nodes)*
        }
    }

    fn node(&self, node: &Node) -> TokenStream {
        let name = format_ident!("{}", node.name);
        let node_name = &node.name;
        let doc = if node.description.is_empty() {
            vec![format!(" {} node.", node.name)]
        } else {
            doc_lines(&node.description)
        };

        let fields = node.members.iter().map(|member| {
            let field = field_ident(member);
            let rust_type = self.rust_type(member);
            quote! { #field: #rust_type }
        });

        // Every member set to its default value, inputs set from the constructor parameters
        let initializers = node
            .members
            .iter()
            .map(|member| {
                let field = field_ident(member);
                match self.default_value(member) {
                    Some(default) => quote! { #field: #default },
                    None => quote! { #field },
                }
            })
            .collect::<Vec<_>>();

        let inputs = node.inputs().map(field_ident).collect::<Vec<_>>();
        let (default, constructor) = if inputs.is_empty() {
            let function = format_ident!("{}", node.name.to_snake_case());
            let function_doc =
                format!(" Creates a [`{}`] node with its default values.", node.name);
            let default = quote! {
                impl Default for #name {
                    fn default() -> Self {
                        Self { #(#initializers,)* }
                    }
                }

                #[doc = #function_doc]
                pub fn #function() -> #name {
                    #name::default()
                }
            };
            (Some(default), None)
        } else {
            let constructor = quote! {
                #[allow(dead_code)]
                pub(crate) fn new(#(#inputs: Node),*) -> Self {
                    Self { #(#initializers,)* }
                }
            };
            (None, Some(constructor))
        };

        let builders = node
            .members
            .iter()
            .filter(|member| !matches!(member.kind, MemberKind::Input))
            .map(|member| self.builder(member));

        let sets = node.members.iter().map(|member| {
            let member_name = &member.name;
            let field = field_ident(member);
            let value = match self.field_type(member) {
                FieldType::Float | FieldType::Int => quote! { self.#field },
                FieldType::Bool => quote! { if self.#field { "True" } else { "False" } },
                FieldType::Enum(_) => quote! { self.#field.name() },
                FieldType::Input | FieldType::Hybrid => quote! { &self.#field },
            };
            quote! { .and_then(|builder| builder.set(#member_name, #value)) }
        });

        quote! {
            #(#[doc = #doc])*
            #[derive(Clone, Debug)]
            pub struct #name {
                #(#fields,)*
            }

            #default

            impl #name {
                #constructor
                #(#builders)*
            }

            impl Generator for #name {
                fn build(&self) -> Node {
                    NodeBuilder::new(#node_name)
                        #(#sets)*
                        .and_then(NodeBuilder::build)
                        .expect("generated from FastNoise2 metadata")
                }
            }
        }
    }

    fn builder(&self, member: &Member) -> TokenStream {
        let field = field_ident(member);
        let parameter = format_ident!("{}", member.name.to_snake_case());
        let method = format_ident!("with_{}", member.name.to_snake_case());

        let mut doc = doc_lines(&member.description);
        if !doc.is_empty() {
            doc.push(String::new());
        }
        doc.push(format!(" Default: `{}`", self.default_doc(member)));

        match self.field_type(member) {
            FieldType::Hybrid => quote! {
                #(#[doc = #doc])*
                pub fn #method(mut self, #parameter: impl Into<Hybrid>) -> Self {
                    self.#field = #parameter.into();
                    self
                }
            },
            _ => {
                let rust_type = self.rust_type(member);
                quote! {
                    #(#[doc = #doc])*
                    pub fn #method(mut self, #parameter: #rust_type) -> Self {
                        self.#field = #parameter;
                        self
                    }
                }
            }
        }
    }

    fn field_type(&self, member: &Member) -> FieldType<'_> {
        match &member.kind {
            MemberKind::Float { .. } => FieldType::Float,
            MemberKind::Int { .. } => FieldType::Int,
            MemberKind::Enum { values, .. } if is_bool(values) => FieldType::Bool,
            MemberKind::Enum { values, .. } => FieldType::Enum(
                self.enums
                    .values()
                    .find(|enum_type| &enum_type.values == values)
                    .expect("enum type collected"),
            ),
            MemberKind::Input => FieldType::Input,
            MemberKind::Hybrid { .. } => FieldType::Hybrid,
        }
    }

    fn rust_type(&self, member: &Member) -> TokenStream {
        match self.field_type(member) {
            FieldType::Float => quote! { f32 },
            FieldType::Int => quote! { i32 },
            FieldType::Bool => quote! { bool },
            FieldType::Enum(enum_type) => {
                let name = format_ident!("{}", enum_type.name);
                quote! { #name }
            }
            FieldType::Input => quote! { Node },
            FieldType::Hybrid => quote! { Hybrid },
        }
    }

    /// Rust expression of the default value, `None` for inputs.
    fn default_value(&self, member: &Member) -> Option<TokenStream> {
        Some(match (&member.kind, self.field_type(member)) {
            (MemberKind::Float { default }, _) => float_literal(*default),
            (MemberKind::Int { default }, _) => int_literal(*default),
            (MemberKind::Enum { default, .. }, FieldType::Bool) => {
                let default = *default == 1;
                quote! { #default }
            }
            (MemberKind::Enum { values, default }, FieldType::Enum(enum_type)) => {
                let name = format_ident!("{}", enum_type.name);
                let variant = format_ident!("{}", values[*default].to_upper_camel_case());
                quote! { #name::#variant }
            }
            (MemberKind::Hybrid { default }, _) => {
                let default = float_literal(*default);
                quote! { Hybrid::Value(#default) }
            }
            _ => return None,
        })
    }

    fn default_doc(&self, member: &Member) -> String {
        match (&member.kind, self.field_type(member)) {
            (MemberKind::Float { default } | MemberKind::Hybrid { default }, _) => {
                format!("{default:?}")
            }
            (MemberKind::Int { default }, _) => default.to_string(),
            (MemberKind::Enum { default, .. }, FieldType::Bool) => (*default == 1).to_string(),
            (MemberKind::Enum { values, default }, FieldType::Enum(enum_type)) => {
                format!(
                    "{}::{}",
                    enum_type.name,
                    values[*default].to_upper_camel_case()
                )
            }
            _ => unreachable!("inputs have no default"),
        }
    }
}

/// Formats generated tokens as a Rust source file.
fn render(tokens: TokenStream) -> String {
    let file = syn::parse2(tokens).expect("generated code is valid Rust");
    format!("{HEADER}{}", space_items(&prettyplease::unparse(&file)))
}

/// Adds a blank line between items, which `prettyplease` puts on consecutive lines.
fn space_items(code: &str) -> String {
    let mut out = String::new();
    let mut previous = "";

    for line in code.lines() {
        let current = line.trim_start();
        let ends_item = previous == "}" || previous.ends_with(';');
        let starts_item = ["///", "#[", "pub ", "pub(", "fn ", "impl ", "use "]
            .iter()
            .any(|start| current.starts_with(start));
        let is_use_group = previous.starts_with("use ") && current.starts_with("use ");
        let after_module_doc = previous.starts_with("//!") && !current.starts_with("//!");

        if (ends_item && starts_item && !is_use_group) || after_module_doc {
            out.push('\n');
        }
        out.push_str(line);
        out.push('\n');
        previous = current;
    }

    out
}

/// Float literal without suffix, always with a decimal point (e.g. `2.0`).
fn float_literal(value: f32) -> TokenStream {
    let literal = Literal::f32_unsuffixed(value.abs());
    if value < 0.0 {
        quote! { -#literal }
    } else {
        quote! { #literal }
    }
}

/// Integer literal without suffix.
fn int_literal(value: i32) -> TokenStream {
    let literal = Literal::u32_unsuffixed(value.unsigned_abs());
    if value < 0 {
        quote! { -#literal }
    } else {
        quote! { #literal }
    }
}

/// Field identifier of a member, escaped if it is a Rust keyword.
fn field_ident(member: &Member) -> Ident {
    let name = member.name.to_snake_case();
    if syn::parse_str::<Ident>(&name).is_ok() {
        Ident::new(&name, Span::call_site())
    } else {
        Ident::new_raw(&name, Span::call_site())
    }
}

fn is_bool(values: &[String]) -> bool {
    values == ["False", "True"]
}

/// Doc comment lines, with a leading space and bare URLs turned into links.
fn doc_lines(text: &str) -> Vec<String> {
    text.lines()
        .map(|line| {
            let line = line
                .split(' ')
                .map(|word| {
                    if word.starts_with("http://") || word.starts_with("https://") {
                        format!("<{word}>")
                    } else {
                        word.to_string()
                    }
                })
                .collect::<Vec<_>>()
                .join(" ");
            format!(" {}", line.trim_end())
        })
        .collect()
}

fn node_links(nodes: &[String]) -> String {
    nodes
        .iter()
        .map(|node| format!("[`{node}`](super::{node})"))
        .collect::<Vec<_>>()
        .join(", ")
}
