// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.
//! Basic Generators nodes.

use super::enums::DistanceFunction;
use crate::node::{Generator, Hybrid, Node, NodeBuilder};

/// Outputs a constant value
#[derive(Clone, Debug)]
pub struct Constant {
    value: f32,
}

impl Default for Constant {
    fn default() -> Self {
        Self { value: 1.0 }
    }
}

/// Creates a [`Constant`] node with its default values.
pub fn constant() -> Constant {
    Constant::default()
}

impl Constant {
    /// Constant output
    ///
    /// Default: `1.0`
    pub fn with_value(mut self, value: f32) -> Self {
        self.value = value;
        self
    }
}

impl Generator for Constant {
    fn build(&self) -> Node {
        NodeBuilder::new("Constant")
            .and_then(|builder| builder.set("Value", self.value))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// White noise generator
#[derive(Clone, Debug)]
pub struct White {
    seed_offset: i32,
    output_min: f32,
    output_max: f32,
}

impl Default for White {
    fn default() -> Self {
        Self {
            seed_offset: 0,
            output_min: -1.0,
            output_max: 1.0,
        }
    }
}

/// Creates a [`White`] node with its default values.
pub fn white() -> White {
    White::default()
}

impl White {
    /// This value is added to the seed before generation
    /// Doesn't affect the seed passed to child nodes
    /// Useful if you have multiple nodes of the same type and want them to give different outputs
    ///
    /// Default: `0`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }

    /// Minimum bound of output range
    ///
    /// Default: `-1.0`
    pub fn with_output_min(mut self, output_min: f32) -> Self {
        self.output_min = output_min;
        self
    }

    /// Maximum bound of output range
    ///
    /// Default: `1.0`
    pub fn with_output_max(mut self, output_max: f32) -> Self {
        self.output_max = output_max;
        self
    }
}

impl Generator for White {
    fn build(&self) -> Node {
        NodeBuilder::new("White")
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| builder.set("Output Min", self.output_min))
            .and_then(|builder| builder.set("Output Max", self.output_max))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Outputs a checkerboard pattern
/// Each checkerboard cell is "Feature Scale" sized in each dimension
#[derive(Clone, Debug)]
pub struct Checkerboard {
    feature_scale: f32,
    output_min: f32,
    output_max: f32,
}

impl Default for Checkerboard {
    fn default() -> Self {
        Self {
            feature_scale: 100.0,
            output_min: -1.0,
            output_max: 1.0,
        }
    }
}

/// Creates a [`Checkerboard`] node with its default values.
pub fn checkerboard() -> Checkerboard {
    Checkerboard::default()
}

impl Checkerboard {
    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// Minimum bound of output range
    ///
    /// Default: `-1.0`
    pub fn with_output_min(mut self, output_min: f32) -> Self {
        self.output_min = output_min;
        self
    }

    /// Maximum bound of output range
    ///
    /// Default: `1.0`
    pub fn with_output_max(mut self, output_max: f32) -> Self {
        self.output_max = output_max;
        self
    }
}

impl Generator for Checkerboard {
    fn build(&self) -> Node {
        NodeBuilder::new("Checkerboard")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Output Min", self.output_min))
            .and_then(|builder| builder.set("Output Max", self.output_max))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Outputs sine wave
#[derive(Clone, Debug)]
pub struct SineWave {
    feature_scale: f32,
    output_min: f32,
    output_max: f32,
}

impl Default for SineWave {
    fn default() -> Self {
        Self {
            feature_scale: 100.0,
            output_min: -1.0,
            output_max: 1.0,
        }
    }
}

/// Creates a [`SineWave`] node with its default values.
pub fn sine_wave() -> SineWave {
    SineWave::default()
}

impl SineWave {
    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// Minimum bound of output range
    ///
    /// Default: `-1.0`
    pub fn with_output_min(mut self, output_min: f32) -> Self {
        self.output_min = output_min;
        self
    }

    /// Maximum bound of output range
    ///
    /// Default: `1.0`
    pub fn with_output_max(mut self, output_max: f32) -> Self {
        self.output_max = output_max;
        self
    }
}

impl Generator for SineWave {
    fn build(&self) -> Node {
        NodeBuilder::new("SineWave")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Output Min", self.output_min))
            .and_then(|builder| builder.set("Output Max", self.output_max))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Takes the input position and does the following per dimension
/// `(input + offset) * multiplier`
/// The output is the sum of all results
#[derive(Clone, Debug)]
pub struct Gradient {
    multiplier_x: f32,
    multiplier_y: f32,
    multiplier_z: f32,
    multiplier_w: f32,
    offset_x: Hybrid,
    offset_y: Hybrid,
    offset_z: Hybrid,
    offset_w: Hybrid,
}

impl Default for Gradient {
    fn default() -> Self {
        Self {
            multiplier_x: 0.0,
            multiplier_y: 0.0,
            multiplier_z: 0.0,
            multiplier_w: 0.0,
            offset_x: Hybrid::Value(0.0),
            offset_y: Hybrid::Value(0.0),
            offset_z: Hybrid::Value(0.0),
            offset_w: Hybrid::Value(0.0),
        }
    }
}

/// Creates a [`Gradient`] node with its default values.
pub fn gradient() -> Gradient {
    Gradient::default()
}

impl Gradient {
    /// Read node description
    ///
    /// Default: `0.0`
    pub fn with_multiplier_x(mut self, multiplier_x: f32) -> Self {
        self.multiplier_x = multiplier_x;
        self
    }

    /// Read node description
    ///
    /// Default: `0.0`
    pub fn with_multiplier_y(mut self, multiplier_y: f32) -> Self {
        self.multiplier_y = multiplier_y;
        self
    }

    /// Read node description
    ///
    /// Default: `0.0`
    pub fn with_multiplier_z(mut self, multiplier_z: f32) -> Self {
        self.multiplier_z = multiplier_z;
        self
    }

    /// Read node description
    ///
    /// Default: `0.0`
    pub fn with_multiplier_w(mut self, multiplier_w: f32) -> Self {
        self.multiplier_w = multiplier_w;
        self
    }

    /// Read node description
    ///
    /// Default: `0.0`
    pub fn with_offset_x(mut self, offset_x: impl Into<Hybrid>) -> Self {
        self.offset_x = offset_x.into();
        self
    }

    /// Read node description
    ///
    /// Default: `0.0`
    pub fn with_offset_y(mut self, offset_y: impl Into<Hybrid>) -> Self {
        self.offset_y = offset_y.into();
        self
    }

    /// Read node description
    ///
    /// Default: `0.0`
    pub fn with_offset_z(mut self, offset_z: impl Into<Hybrid>) -> Self {
        self.offset_z = offset_z.into();
        self
    }

    /// Read node description
    ///
    /// Default: `0.0`
    pub fn with_offset_w(mut self, offset_w: impl Into<Hybrid>) -> Self {
        self.offset_w = offset_w.into();
        self
    }
}

impl Generator for Gradient {
    fn build(&self) -> Node {
        NodeBuilder::new("Gradient")
            .and_then(|builder| builder.set("Multiplier X", self.multiplier_x))
            .and_then(|builder| builder.set("Multiplier Y", self.multiplier_y))
            .and_then(|builder| builder.set("Multiplier Z", self.multiplier_z))
            .and_then(|builder| builder.set("Multiplier W", self.multiplier_w))
            .and_then(|builder| builder.set("Offset X", &self.offset_x))
            .and_then(|builder| builder.set("Offset Y", &self.offset_y))
            .and_then(|builder| builder.set("Offset Z", &self.offset_z))
            .and_then(|builder| builder.set("Offset W", &self.offset_w))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Outputs distance between point and input position
/// Distance is calculated in current domain space,
/// ie affected by Domain Modifiers/Warping
#[derive(Clone, Debug)]
pub struct DistanceToPoint {
    distance_function: DistanceFunction,
    point_x: Hybrid,
    point_y: Hybrid,
    point_z: Hybrid,
    point_w: Hybrid,
    minkowski_p: Hybrid,
}

impl Default for DistanceToPoint {
    fn default() -> Self {
        Self {
            distance_function: DistanceFunction::Euclidean,
            point_x: Hybrid::Value(0.0),
            point_y: Hybrid::Value(0.0),
            point_z: Hybrid::Value(0.0),
            point_w: Hybrid::Value(0.0),
            minkowski_p: Hybrid::Value(1.5),
        }
    }
}

/// Creates a [`DistanceToPoint`] node with its default values.
pub fn distance_to_point() -> DistanceToPoint {
    DistanceToPoint::default()
}

impl DistanceToPoint {
    /// Default: `DistanceFunction::Euclidean`
    pub fn with_distance_function(
        mut self,
        distance_function: DistanceFunction,
    ) -> Self {
        self.distance_function = distance_function;
        self
    }

    /// Point in current domain space
    ///
    /// Default: `0.0`
    pub fn with_point_x(mut self, point_x: impl Into<Hybrid>) -> Self {
        self.point_x = point_x.into();
        self
    }

    /// Point in current domain space
    ///
    /// Default: `0.0`
    pub fn with_point_y(mut self, point_y: impl Into<Hybrid>) -> Self {
        self.point_y = point_y.into();
        self
    }

    /// Point in current domain space
    ///
    /// Default: `0.0`
    pub fn with_point_z(mut self, point_z: impl Into<Hybrid>) -> Self {
        self.point_z = point_z.into();
        self
    }

    /// Point in current domain space
    ///
    /// Default: `0.0`
    pub fn with_point_w(mut self, point_w: impl Into<Hybrid>) -> Self {
        self.point_w = point_w.into();
        self
    }

    /// Only affects Minkowski distance function
    /// 1 = Manhattan
    /// 2 = Euclidean
    ///
    /// Default: `1.5`
    pub fn with_minkowski_p(mut self, minkowski_p: impl Into<Hybrid>) -> Self {
        self.minkowski_p = minkowski_p.into();
        self
    }
}

impl Generator for DistanceToPoint {
    fn build(&self) -> Node {
        NodeBuilder::new("DistanceToPoint")
            .and_then(|builder| {
                builder.set("Distance Function", self.distance_function.name())
            })
            .and_then(|builder| builder.set("Point X", &self.point_x))
            .and_then(|builder| builder.set("Point Y", &self.point_y))
            .and_then(|builder| builder.set("Point Z", &self.point_z))
            .and_then(|builder| builder.set("Point W", &self.point_w))
            .and_then(|builder| builder.set("Minkowski P", &self.minkowski_p))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}
