// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.
//! Blends nodes.

use super::enums::Interpolation;
use crate::node::{Generator, Hybrid, Node, NodeBuilder};

/// Min node.
#[derive(Clone, Debug)]
pub struct Min {
    lhs: Node,
    rhs: Hybrid,
}

impl Min {
    pub(crate) fn new(lhs: Node) -> Self {
        Self {
            lhs,
            rhs: Hybrid::Value(0.0),
        }
    }

    /// Default: `0.0`
    pub fn with_rhs(mut self, rhs: impl Into<Hybrid>) -> Self {
        self.rhs = rhs.into();
        self
    }
}

impl Generator for Min {
    fn build(&self) -> Node {
        NodeBuilder::new("Min")
            .and_then(|builder| builder.set("LHS", &self.lhs))
            .and_then(|builder| builder.set("RHS", &self.rhs))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Max node.
#[derive(Clone, Debug)]
pub struct Max {
    lhs: Node,
    rhs: Hybrid,
}

impl Max {
    pub(crate) fn new(lhs: Node) -> Self {
        Self {
            lhs,
            rhs: Hybrid::Value(0.0),
        }
    }

    /// Default: `0.0`
    pub fn with_rhs(mut self, rhs: impl Into<Hybrid>) -> Self {
        self.rhs = rhs.into();
        self
    }
}

impl Generator for Max {
    fn build(&self) -> Node {
        NodeBuilder::new("Max")
            .and_then(|builder| builder.set("LHS", &self.lhs))
            .and_then(|builder| builder.set("RHS", &self.rhs))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Quadratic Smooth Minimum
/// Smoothes the transition between the 2 inputs
/// For explanation see:
/// <https://iquilezles.org/articles/smin/>
#[derive(Clone, Debug)]
pub struct MinSmooth {
    lhs: Node,
    rhs: Hybrid,
    smoothness: Hybrid,
}

impl MinSmooth {
    pub(crate) fn new(lhs: Node) -> Self {
        Self {
            lhs,
            rhs: Hybrid::Value(0.0),
            smoothness: Hybrid::Value(0.1),
        }
    }

    /// Default: `0.0`
    pub fn with_rhs(mut self, rhs: impl Into<Hybrid>) -> Self {
        self.rhs = rhs.into();
        self
    }

    /// Default: `0.1`
    pub fn with_smoothness(mut self, smoothness: impl Into<Hybrid>) -> Self {
        self.smoothness = smoothness.into();
        self
    }
}

impl Generator for MinSmooth {
    fn build(&self) -> Node {
        NodeBuilder::new("MinSmooth")
            .and_then(|builder| builder.set("LHS", &self.lhs))
            .and_then(|builder| builder.set("RHS", &self.rhs))
            .and_then(|builder| builder.set("Smoothness", &self.smoothness))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Quadratic Smooth Maximum
/// Smoothes the transition between the 2 inputs
/// For explanation see:
/// <https://iquilezles.org/articles/smin/>
#[derive(Clone, Debug)]
pub struct MaxSmooth {
    lhs: Node,
    rhs: Hybrid,
    smoothness: Hybrid,
}

impl MaxSmooth {
    pub(crate) fn new(lhs: Node) -> Self {
        Self {
            lhs,
            rhs: Hybrid::Value(0.0),
            smoothness: Hybrid::Value(0.1),
        }
    }

    /// Default: `0.0`
    pub fn with_rhs(mut self, rhs: impl Into<Hybrid>) -> Self {
        self.rhs = rhs.into();
        self
    }

    /// Default: `0.1`
    pub fn with_smoothness(mut self, smoothness: impl Into<Hybrid>) -> Self {
        self.smoothness = smoothness.into();
        self
    }
}

impl Generator for MaxSmooth {
    fn build(&self) -> Node {
        NodeBuilder::new("MaxSmooth")
            .and_then(|builder| builder.set("LHS", &self.lhs))
            .and_then(|builder| builder.set("RHS", &self.rhs))
            .and_then(|builder| builder.set("Smoothness", &self.smoothness))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Equivalent to std::powf( value, pow )
#[derive(Clone, Debug)]
pub struct PowFloat {
    value: Hybrid,
    pow: Hybrid,
}

impl Default for PowFloat {
    fn default() -> Self {
        Self {
            value: Hybrid::Value(2.0),
            pow: Hybrid::Value(2.0),
        }
    }
}

/// Creates a [`PowFloat`] node with its default values.
pub fn pow_float() -> PowFloat {
    PowFloat::default()
}

impl PowFloat {
    /// Default: `2.0`
    pub fn with_value(mut self, value: impl Into<Hybrid>) -> Self {
        self.value = value.into();
        self
    }

    /// Default: `2.0`
    pub fn with_pow(mut self, pow: impl Into<Hybrid>) -> Self {
        self.pow = pow.into();
        self
    }
}

impl Generator for PowFloat {
    fn build(&self) -> Node {
        NodeBuilder::new("PowFloat")
            .and_then(|builder| builder.set("Value", &self.value))
            .and_then(|builder| builder.set("Pow", &self.pow))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Faster than PowFloat node but only for int powers
#[derive(Clone, Debug)]
pub struct PowInt {
    pow: i32,
    value: Node,
}

impl PowInt {
    pub(crate) fn new(value: Node) -> Self {
        Self { pow: 2, value }
    }

    /// Default: `2`
    pub fn with_pow(mut self, pow: i32) -> Self {
        self.pow = pow;
        self
    }
}

impl Generator for PowInt {
    fn build(&self) -> Node {
        NodeBuilder::new("PowInt")
            .and_then(|builder| builder.set("Pow", self.pow))
            .and_then(|builder| builder.set("Value", &self.value))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Output fades between inputs A and B
/// Fade Min = 100% A
/// Fade Max = 100% B
#[derive(Clone, Debug)]
pub struct Fade {
    interpolation: Interpolation,
    a: Node,
    b: Node,
    fade: Hybrid,
    fade_min: Hybrid,
    fade_max: Hybrid,
}

impl Fade {
    pub(crate) fn new(a: Node, b: Node) -> Self {
        Self {
            interpolation: Interpolation::Linear,
            a,
            b,
            fade: Hybrid::Value(0.0),
            fade_min: Hybrid::Value(-1.0),
            fade_max: Hybrid::Value(1.0),
        }
    }

    /// Easing function
    ///
    /// Default: `Interpolation::Linear`
    pub fn with_interpolation(mut self, interpolation: Interpolation) -> Self {
        self.interpolation = interpolation;
        self
    }

    /// Default: `0.0`
    pub fn with_fade(mut self, fade: impl Into<Hybrid>) -> Self {
        self.fade = fade.into();
        self
    }

    /// Default: `-1.0`
    pub fn with_fade_min(mut self, fade_min: impl Into<Hybrid>) -> Self {
        self.fade_min = fade_min.into();
        self
    }

    /// Default: `1.0`
    pub fn with_fade_max(mut self, fade_max: impl Into<Hybrid>) -> Self {
        self.fade_max = fade_max.into();
        self
    }
}

impl Generator for Fade {
    fn build(&self) -> Node {
        NodeBuilder::new("Fade")
            .and_then(|builder| builder.set("Interpolation", self.interpolation.name()))
            .and_then(|builder| builder.set("A", &self.a))
            .and_then(|builder| builder.set("B", &self.b))
            .and_then(|builder| builder.set("Fade", &self.fade))
            .and_then(|builder| builder.set("Fade Min", &self.fade_min))
            .and_then(|builder| builder.set("Fade Max", &self.fade_max))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}
