// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.
//! Coherent Noise nodes.

use super::enums::{DistanceFunction, ReturnType};
use crate::node::{Generator, Hybrid, Node, NodeBuilder};

/// Smooth gradient noise from an N dimensional simplex grid
/// Developed by Ken Perlin in 2001
#[derive(Clone, Debug)]
pub struct Simplex {
    feature_scale: f32,
    seed_offset: i32,
    output_min: f32,
    output_max: f32,
}

impl Default for Simplex {
    fn default() -> Self {
        Self {
            feature_scale: 100.0,
            seed_offset: 0,
            output_min: -1.0,
            output_max: 1.0,
        }
    }
}

/// Creates a [`Simplex`] node with its default values.
pub fn simplex() -> Simplex {
    Simplex::default()
}

impl Simplex {
    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// This value is added to the seed before generation
    /// Doesn't affect the seed passed to child nodes
    /// Useful if you have multiple nodes of the same type and want them to give different outputs
    ///
    /// Default: `0`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }

    /// Minimum bound of output range
    ///
    /// Default: `-1.0`
    pub fn with_output_min(mut self, output_min: f32) -> Self {
        self.output_min = output_min;
        self
    }

    /// Maximum bound of output range
    ///
    /// Default: `1.0`
    pub fn with_output_max(mut self, output_max: f32) -> Self {
        self.output_max = output_max;
        self
    }
}

impl Generator for Simplex {
    fn build(&self) -> Node {
        NodeBuilder::new("Simplex")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| builder.set("Output Min", self.output_min))
            .and_then(|builder| builder.set("Output Max", self.output_max))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Extra smooth gradient noise from an N dimensional simplex grid
/// Slower to generate than Simplex noise
/// Developed by K.jpg
#[derive(Clone, Debug)]
pub struct SuperSimplex {
    feature_scale: f32,
    seed_offset: i32,
    output_min: f32,
    output_max: f32,
}

impl Default for SuperSimplex {
    fn default() -> Self {
        Self {
            feature_scale: 100.0,
            seed_offset: 0,
            output_min: -1.0,
            output_max: 1.0,
        }
    }
}

/// Creates a [`SuperSimplex`] node with its default values.
pub fn super_simplex() -> SuperSimplex {
    SuperSimplex::default()
}

impl SuperSimplex {
    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// This value is added to the seed before generation
    /// Doesn't affect the seed passed to child nodes
    /// Useful if you have multiple nodes of the same type and want them to give different outputs
    ///
    /// Default: `0`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }

    /// Minimum bound of output range
    ///
    /// Default: `-1.0`
    pub fn with_output_min(mut self, output_min: f32) -> Self {
        self.output_min = output_min;
        self
    }

    /// Maximum bound of output range
    ///
    /// Default: `1.0`
    pub fn with_output_max(mut self, output_max: f32) -> Self {
        self.output_max = output_max;
        self
    }
}

impl Generator for SuperSimplex {
    fn build(&self) -> Node {
        NodeBuilder::new("SuperSimplex")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| builder.set("Output Min", self.output_min))
            .and_then(|builder| builder.set("Output Max", self.output_max))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Smooth gradient noise from N dimensional grid
/// Developed by Ken Perlin in 1983
#[derive(Clone, Debug)]
pub struct Perlin {
    feature_scale: f32,
    seed_offset: i32,
    output_min: f32,
    output_max: f32,
}

impl Default for Perlin {
    fn default() -> Self {
        Self {
            feature_scale: 100.0,
            seed_offset: 0,
            output_min: -1.0,
            output_max: 1.0,
        }
    }
}

/// Creates a [`Perlin`] node with its default values.
pub fn perlin() -> Perlin {
    Perlin::default()
}

impl Perlin {
    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// This value is added to the seed before generation
    /// Doesn't affect the seed passed to child nodes
    /// Useful if you have multiple nodes of the same type and want them to give different outputs
    ///
    /// Default: `0`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }

    /// Minimum bound of output range
    ///
    /// Default: `-1.0`
    pub fn with_output_min(mut self, output_min: f32) -> Self {
        self.output_min = output_min;
        self
    }

    /// Maximum bound of output range
    ///
    /// Default: `1.0`
    pub fn with_output_max(mut self, output_max: f32) -> Self {
        self.output_max = output_max;
        self
    }
}

impl Generator for Perlin {
    fn build(&self) -> Node {
        NodeBuilder::new("Perlin")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| builder.set("Output Min", self.output_min))
            .and_then(|builder| builder.set("Output Max", self.output_max))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Smooth gradient noise from N dimensional grid
#[derive(Clone, Debug)]
pub struct Value {
    feature_scale: f32,
    seed_offset: i32,
    output_min: f32,
    output_max: f32,
}

impl Default for Value {
    fn default() -> Self {
        Self {
            feature_scale: 100.0,
            seed_offset: 0,
            output_min: -1.0,
            output_max: 1.0,
        }
    }
}

/// Creates a [`Value`] node with its default values.
pub fn value() -> Value {
    Value::default()
}

impl Value {
    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// This value is added to the seed before generation
    /// Doesn't affect the seed passed to child nodes
    /// Useful if you have multiple nodes of the same type and want them to give different outputs
    ///
    /// Default: `0`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }

    /// Minimum bound of output range
    ///
    /// Default: `-1.0`
    pub fn with_output_min(mut self, output_min: f32) -> Self {
        self.output_min = output_min;
        self
    }

    /// Maximum bound of output range
    ///
    /// Default: `1.0`
    pub fn with_output_max(mut self, output_max: f32) -> Self {
        self.output_max = output_max;
        self
    }
}

impl Generator for Value {
    fn build(&self) -> Node {
        NodeBuilder::new("Value")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| builder.set("Output Min", self.output_min))
            .and_then(|builder| builder.set("Output Max", self.output_max))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Returns value of Nth closest cell
/// Value is generated using white noise
#[derive(Clone, Debug)]
pub struct CellularValue {
    feature_scale: f32,
    seed_offset: i32,
    output_min: f32,
    output_max: f32,
    distance_function: DistanceFunction,
    value_index: i32,
    minkowski_p: Hybrid,
    grid_jitter: Hybrid,
    size_jitter: Hybrid,
}

impl Default for CellularValue {
    fn default() -> Self {
        Self {
            feature_scale: 100.0,
            seed_offset: 0,
            output_min: -1.0,
            output_max: 1.0,
            distance_function: DistanceFunction::EuclideanSquared,
            value_index: 0,
            minkowski_p: Hybrid::Value(1.5),
            grid_jitter: Hybrid::Value(1.0),
            size_jitter: Hybrid::Value(0.0),
        }
    }
}

/// Creates a [`CellularValue`] node with its default values.
pub fn cellular_value() -> CellularValue {
    CellularValue::default()
}

impl CellularValue {
    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// This value is added to the seed before generation
    /// Doesn't affect the seed passed to child nodes
    /// Useful if you have multiple nodes of the same type and want them to give different outputs
    ///
    /// Default: `0`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }

    /// Minimum bound of output range
    ///
    /// Default: `-1.0`
    pub fn with_output_min(mut self, output_min: f32) -> Self {
        self.output_min = output_min;
        self
    }

    /// Maximum bound of output range
    ///
    /// Default: `1.0`
    pub fn with_output_max(mut self, output_max: f32) -> Self {
        self.output_max = output_max;
        self
    }

    /// How distance to closest cells is calculated
    /// Hybrid is EuclideanSquared + Manhattan
    ///
    /// Default: `DistanceFunction::EuclideanSquared`
    pub fn with_distance_function(
        mut self,
        distance_function: DistanceFunction,
    ) -> Self {
        self.distance_function = distance_function;
        self
    }

    /// Nth closest cell
    ///
    /// Default: `0`
    ///
    /// Node Editor range: `0..=3`, not enforced by FastNoise2
    pub fn with_value_index(mut self, value_index: i32) -> Self {
        self.value_index = value_index;
        self
    }

    /// Only affects Minkowski distance function
    /// 1 = Manhattan
    /// 2 = Euclidean
    ///
    /// Default: `1.5`
    pub fn with_minkowski_p(mut self, minkowski_p: impl Into<Hybrid>) -> Self {
        self.minkowski_p = minkowski_p.into();
        self
    }

    /// How much to displace cells from their uniform grid position
    /// 0.0 will output a uniform grid
    /// Above 1.0 will cause grid artifacts
    ///
    /// Default: `1.0`
    pub fn with_grid_jitter(mut self, grid_jitter: impl Into<Hybrid>) -> Self {
        self.grid_jitter = grid_jitter.into();
        self
    }

    /// Apply a random multiplier each cell's distance calculation
    /// Causes more variation in cell size
    /// Can cause grid artifacts
    ///
    /// Default: `0.0`
    pub fn with_size_jitter(mut self, size_jitter: impl Into<Hybrid>) -> Self {
        self.size_jitter = size_jitter.into();
        self
    }
}

impl Generator for CellularValue {
    fn build(&self) -> Node {
        NodeBuilder::new("CellularValue")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| builder.set("Output Min", self.output_min))
            .and_then(|builder| builder.set("Output Max", self.output_max))
            .and_then(|builder| {
                builder.set("Distance Function", self.distance_function.name())
            })
            .and_then(|builder| builder.set("Value Index", self.value_index))
            .and_then(|builder| builder.set("Minkowski P", &self.minkowski_p))
            .and_then(|builder| builder.set("Grid Jitter", &self.grid_jitter))
            .and_then(|builder| builder.set("Size Jitter", &self.size_jitter))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Returns distance of Nth closest cell
/// Distance of Index0 and Index1 are combined according to return type
/// Returned value is always positive except when using Index0Sub1 and Index0 > Index1
#[derive(Clone, Debug)]
pub struct CellularDistance {
    feature_scale: f32,
    seed_offset: i32,
    output_min: f32,
    output_max: f32,
    distance_function: DistanceFunction,
    distance_index_0: i32,
    distance_index_1: i32,
    return_type: ReturnType,
    minkowski_p: Hybrid,
    grid_jitter: Hybrid,
    size_jitter: Hybrid,
}

impl Default for CellularDistance {
    fn default() -> Self {
        Self {
            feature_scale: 100.0,
            seed_offset: 0,
            output_min: -1.0,
            output_max: 1.0,
            distance_function: DistanceFunction::EuclideanSquared,
            distance_index_0: 0,
            distance_index_1: 1,
            return_type: ReturnType::Index0,
            minkowski_p: Hybrid::Value(1.5),
            grid_jitter: Hybrid::Value(1.0),
            size_jitter: Hybrid::Value(0.0),
        }
    }
}

/// Creates a [`CellularDistance`] node with its default values.
pub fn cellular_distance() -> CellularDistance {
    CellularDistance::default()
}

impl CellularDistance {
    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// This value is added to the seed before generation
    /// Doesn't affect the seed passed to child nodes
    /// Useful if you have multiple nodes of the same type and want them to give different outputs
    ///
    /// Default: `0`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }

    /// Minimum bound of output range
    ///
    /// Default: `-1.0`
    pub fn with_output_min(mut self, output_min: f32) -> Self {
        self.output_min = output_min;
        self
    }

    /// Maximum bound of output range
    ///
    /// Default: `1.0`
    pub fn with_output_max(mut self, output_max: f32) -> Self {
        self.output_max = output_max;
        self
    }

    /// How distance to closest cells is calculated
    /// Hybrid is EuclideanSquared + Manhattan
    ///
    /// Default: `DistanceFunction::EuclideanSquared`
    pub fn with_distance_function(
        mut self,
        distance_function: DistanceFunction,
    ) -> Self {
        self.distance_function = distance_function;
        self
    }

    /// Nth closest cell
    ///
    /// Default: `0`
    ///
    /// Node Editor range: `0..=3`, not enforced by FastNoise2
    pub fn with_distance_index_0(mut self, distance_index_0: i32) -> Self {
        self.distance_index_0 = distance_index_0;
        self
    }

    /// Nth closest cell
    ///
    /// Default: `1`
    ///
    /// Node Editor range: `0..=3`, not enforced by FastNoise2
    pub fn with_distance_index_1(mut self, distance_index_1: i32) -> Self {
        self.distance_index_1 = distance_index_1;
        self
    }

    /// How to combine Index 0 & Index 1
    ///
    /// Default: `ReturnType::Index0`
    pub fn with_return_type(mut self, return_type: ReturnType) -> Self {
        self.return_type = return_type;
        self
    }

    /// Only affects Minkowski distance function
    /// 1 = Manhattan
    /// 2 = Euclidean
    ///
    /// Default: `1.5`
    pub fn with_minkowski_p(mut self, minkowski_p: impl Into<Hybrid>) -> Self {
        self.minkowski_p = minkowski_p.into();
        self
    }

    /// How much to displace cells from their uniform grid position
    /// 0.0 will output a uniform grid
    /// Above 1.0 will cause grid artifacts
    ///
    /// Default: `1.0`
    pub fn with_grid_jitter(mut self, grid_jitter: impl Into<Hybrid>) -> Self {
        self.grid_jitter = grid_jitter.into();
        self
    }

    /// Apply a random multiplier each cell's distance calculation
    /// Causes more variation in cell size
    /// Can cause grid artifacts
    ///
    /// Default: `0.0`
    pub fn with_size_jitter(mut self, size_jitter: impl Into<Hybrid>) -> Self {
        self.size_jitter = size_jitter.into();
        self
    }
}

impl Generator for CellularDistance {
    fn build(&self) -> Node {
        NodeBuilder::new("CellularDistance")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| builder.set("Output Min", self.output_min))
            .and_then(|builder| builder.set("Output Max", self.output_max))
            .and_then(|builder| {
                builder.set("Distance Function", self.distance_function.name())
            })
            .and_then(|builder| builder.set("Distance Index 0", self.distance_index_0))
            .and_then(|builder| builder.set("Distance Index 1", self.distance_index_1))
            .and_then(|builder| builder.set("Return Type", self.return_type.name()))
            .and_then(|builder| builder.set("Minkowski P", &self.minkowski_p))
            .and_then(|builder| builder.set("Grid Jitter", &self.grid_jitter))
            .and_then(|builder| builder.set("Size Jitter", &self.size_jitter))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Returns value of closest cell
/// Value is generated at the cell center using the lookup source
#[derive(Clone, Debug)]
pub struct CellularLookup {
    feature_scale: f32,
    seed_offset: i32,
    distance_function: DistanceFunction,
    lookup: Node,
    minkowski_p: Hybrid,
    grid_jitter: Hybrid,
    size_jitter: Hybrid,
}

impl CellularLookup {
    pub(crate) fn new(lookup: Node) -> Self {
        Self {
            feature_scale: 100.0,
            seed_offset: 0,
            distance_function: DistanceFunction::EuclideanSquared,
            lookup,
            minkowski_p: Hybrid::Value(1.5),
            grid_jitter: Hybrid::Value(1.0),
            size_jitter: Hybrid::Value(0.0),
        }
    }

    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// This value is added to the seed before generation
    /// Doesn't affect the seed passed to child nodes
    /// Useful if you have multiple nodes of the same type and want them to give different outputs
    ///
    /// Default: `0`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }

    /// How distance to closest cells is calculated
    /// Hybrid is EuclideanSquared + Manhattan
    ///
    /// Default: `DistanceFunction::EuclideanSquared`
    pub fn with_distance_function(
        mut self,
        distance_function: DistanceFunction,
    ) -> Self {
        self.distance_function = distance_function;
        self
    }

    /// Only affects Minkowski distance function
    /// 1 = Manhattan
    /// 2 = Euclidean
    ///
    /// Default: `1.5`
    pub fn with_minkowski_p(mut self, minkowski_p: impl Into<Hybrid>) -> Self {
        self.minkowski_p = minkowski_p.into();
        self
    }

    /// How much to displace cells from their uniform grid position
    /// 0.0 will output a uniform grid
    /// Above 1.0 will cause grid artifacts
    ///
    /// Default: `1.0`
    pub fn with_grid_jitter(mut self, grid_jitter: impl Into<Hybrid>) -> Self {
        self.grid_jitter = grid_jitter.into();
        self
    }

    /// Apply a random multiplier each cell's distance calculation
    /// Causes more variation in cell size
    /// Can cause grid artifacts
    ///
    /// Default: `0.0`
    pub fn with_size_jitter(mut self, size_jitter: impl Into<Hybrid>) -> Self {
        self.size_jitter = size_jitter.into();
        self
    }
}

impl Generator for CellularLookup {
    fn build(&self) -> Node {
        NodeBuilder::new("CellularLookup")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| {
                builder.set("Distance Function", self.distance_function.name())
            })
            .and_then(|builder| builder.set("Lookup", &self.lookup))
            .and_then(|builder| builder.set("Minkowski P", &self.minkowski_p))
            .and_then(|builder| builder.set("Grid Jitter", &self.grid_jitter))
            .and_then(|builder| builder.set("Size Jitter", &self.size_jitter))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}
