// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.
//! Domain Warp nodes.

use super::enums::VectorizationScheme;
use crate::node::{Generator, Hybrid, Node, NodeBuilder};

/// Warp the domain using a simplex grid
/// The warped position is used when generating the attached source node
/// This node does not change the output value of the source node
/// A higher quality domain warp compared to DomainWarpGradient at the cost of performance
#[derive(Clone, Debug)]
pub struct DomainWarpSimplex {
    feature_scale: f32,
    seed_offset: i32,
    amplitude_scaling_x: f32,
    amplitude_scaling_y: f32,
    amplitude_scaling_z: f32,
    amplitude_scaling_w: f32,
    vectorization_scheme: VectorizationScheme,
    source: Node,
    warp_amplitude: Hybrid,
}

impl DomainWarpSimplex {
    #[allow(dead_code)]
    pub(crate) fn new(source: Node) -> Self {
        Self {
            feature_scale: 100.0,
            seed_offset: 0,
            amplitude_scaling_x: 1.0,
            amplitude_scaling_y: 1.0,
            amplitude_scaling_z: 1.0,
            amplitude_scaling_w: 1.0,
            vectorization_scheme: VectorizationScheme::OrthogonalGradientMatrix,
            source,
            warp_amplitude: Hybrid::Value(50.0),
        }
    }

    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// This value is added to the seed before generation
    /// Doesn't affect the seed passed to child nodes
    /// Useful if you have multiple nodes of the same type and want them to give different outputs
    ///
    /// Default: `0`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_x(mut self, amplitude_scaling_x: f32) -> Self {
        self.amplitude_scaling_x = amplitude_scaling_x;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_y(mut self, amplitude_scaling_y: f32) -> Self {
        self.amplitude_scaling_y = amplitude_scaling_y;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_z(mut self, amplitude_scaling_z: f32) -> Self {
        self.amplitude_scaling_z = amplitude_scaling_z;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_w(mut self, amplitude_scaling_w: f32) -> Self {
        self.amplitude_scaling_w = amplitude_scaling_w;
        self
    }

    /// Construction used by the noise to produce a vector output
    ///
    /// Default: `VectorizationScheme::OrthogonalGradientMatrix`
    pub fn with_vectorization_scheme(
        mut self,
        vectorization_scheme: VectorizationScheme,
    ) -> Self {
        self.vectorization_scheme = vectorization_scheme;
        self
    }

    /// Maximum (euclidean) distance the position can be moved from it's original location
    ///
    /// Default: `50.0`
    pub fn with_warp_amplitude(mut self, warp_amplitude: impl Into<Hybrid>) -> Self {
        self.warp_amplitude = warp_amplitude.into();
        self
    }
}

impl Generator for DomainWarpSimplex {
    fn build(&self) -> Node {
        NodeBuilder::new("DomainWarpSimplex")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| {
                builder.set("Amplitude Scaling X", self.amplitude_scaling_x)
            })
            .and_then(|builder| {
                builder.set("Amplitude Scaling Y", self.amplitude_scaling_y)
            })
            .and_then(|builder| {
                builder.set("Amplitude Scaling Z", self.amplitude_scaling_z)
            })
            .and_then(|builder| {
                builder.set("Amplitude Scaling W", self.amplitude_scaling_w)
            })
            .and_then(|builder| {
                builder.set("Vectorization Scheme", self.vectorization_scheme.name())
            })
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(|builder| builder.set("Warp Amplitude", &self.warp_amplitude))
            .and_then(NodeBuilder::build)
            .expect("generated from FastNoise2 metadata")
    }
}

/// Warp the domain using a smooth simplex grid
/// The warped position is used when generating the attached source node
/// This node does not change the output value of the source node
/// A higher quality smoother warp compared to DomainWarpSimplex at the cost of performance
#[derive(Clone, Debug)]
pub struct DomainWarpSuperSimplex {
    feature_scale: f32,
    seed_offset: i32,
    amplitude_scaling_x: f32,
    amplitude_scaling_y: f32,
    amplitude_scaling_z: f32,
    amplitude_scaling_w: f32,
    vectorization_scheme: VectorizationScheme,
    source: Node,
    warp_amplitude: Hybrid,
}

impl DomainWarpSuperSimplex {
    #[allow(dead_code)]
    pub(crate) fn new(source: Node) -> Self {
        Self {
            feature_scale: 100.0,
            seed_offset: 0,
            amplitude_scaling_x: 1.0,
            amplitude_scaling_y: 1.0,
            amplitude_scaling_z: 1.0,
            amplitude_scaling_w: 1.0,
            vectorization_scheme: VectorizationScheme::OrthogonalGradientMatrix,
            source,
            warp_amplitude: Hybrid::Value(50.0),
        }
    }

    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// This value is added to the seed before generation
    /// Doesn't affect the seed passed to child nodes
    /// Useful if you have multiple nodes of the same type and want them to give different outputs
    ///
    /// Default: `0`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_x(mut self, amplitude_scaling_x: f32) -> Self {
        self.amplitude_scaling_x = amplitude_scaling_x;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_y(mut self, amplitude_scaling_y: f32) -> Self {
        self.amplitude_scaling_y = amplitude_scaling_y;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_z(mut self, amplitude_scaling_z: f32) -> Self {
        self.amplitude_scaling_z = amplitude_scaling_z;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_w(mut self, amplitude_scaling_w: f32) -> Self {
        self.amplitude_scaling_w = amplitude_scaling_w;
        self
    }

    /// Construction used by the noise to produce a vector output
    ///
    /// Default: `VectorizationScheme::OrthogonalGradientMatrix`
    pub fn with_vectorization_scheme(
        mut self,
        vectorization_scheme: VectorizationScheme,
    ) -> Self {
        self.vectorization_scheme = vectorization_scheme;
        self
    }

    /// Maximum (euclidean) distance the position can be moved from it's original location
    ///
    /// Default: `50.0`
    pub fn with_warp_amplitude(mut self, warp_amplitude: impl Into<Hybrid>) -> Self {
        self.warp_amplitude = warp_amplitude.into();
        self
    }
}

impl Generator for DomainWarpSuperSimplex {
    fn build(&self) -> Node {
        NodeBuilder::new("DomainWarpSuperSimplex")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| {
                builder.set("Amplitude Scaling X", self.amplitude_scaling_x)
            })
            .and_then(|builder| {
                builder.set("Amplitude Scaling Y", self.amplitude_scaling_y)
            })
            .and_then(|builder| {
                builder.set("Amplitude Scaling Z", self.amplitude_scaling_z)
            })
            .and_then(|builder| {
                builder.set("Amplitude Scaling W", self.amplitude_scaling_w)
            })
            .and_then(|builder| {
                builder.set("Vectorization Scheme", self.vectorization_scheme.name())
            })
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(|builder| builder.set("Warp Amplitude", &self.warp_amplitude))
            .and_then(NodeBuilder::build)
            .expect("generated from FastNoise2 metadata")
    }
}

/// Warps the input position using a simple uniform grid gradient, similar to perlin noise gradients.
/// The warped position is used when generating the attached source node
/// This node does not change the output value of the source node
#[derive(Clone, Debug)]
pub struct DomainWarpGradient {
    feature_scale: f32,
    seed_offset: i32,
    amplitude_scaling_x: f32,
    amplitude_scaling_y: f32,
    amplitude_scaling_z: f32,
    amplitude_scaling_w: f32,
    source: Node,
    warp_amplitude: Hybrid,
}

impl DomainWarpGradient {
    #[allow(dead_code)]
    pub(crate) fn new(source: Node) -> Self {
        Self {
            feature_scale: 100.0,
            seed_offset: 0,
            amplitude_scaling_x: 1.0,
            amplitude_scaling_y: 1.0,
            amplitude_scaling_z: 1.0,
            amplitude_scaling_w: 1.0,
            source,
            warp_amplitude: Hybrid::Value(50.0),
        }
    }

    /// Effectively `1.0 / frequency`
    ///
    /// Default: `100.0`
    pub fn with_feature_scale(mut self, feature_scale: f32) -> Self {
        self.feature_scale = feature_scale;
        self
    }

    /// This value is added to the seed before generation
    /// Doesn't affect the seed passed to child nodes
    /// Useful if you have multiple nodes of the same type and want them to give different outputs
    ///
    /// Default: `0`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_x(mut self, amplitude_scaling_x: f32) -> Self {
        self.amplitude_scaling_x = amplitude_scaling_x;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_y(mut self, amplitude_scaling_y: f32) -> Self {
        self.amplitude_scaling_y = amplitude_scaling_y;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_z(mut self, amplitude_scaling_z: f32) -> Self {
        self.amplitude_scaling_z = amplitude_scaling_z;
        self
    }

    /// Default: `1.0`
    pub fn with_amplitude_scaling_w(mut self, amplitude_scaling_w: f32) -> Self {
        self.amplitude_scaling_w = amplitude_scaling_w;
        self
    }

    /// Maximum (euclidean) distance the position can be moved from it's original location
    ///
    /// Default: `50.0`
    pub fn with_warp_amplitude(mut self, warp_amplitude: impl Into<Hybrid>) -> Self {
        self.warp_amplitude = warp_amplitude.into();
        self
    }
}

impl Generator for DomainWarpGradient {
    fn build(&self) -> Node {
        NodeBuilder::new("DomainWarpGradient")
            .and_then(|builder| builder.set("Feature Scale", self.feature_scale))
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| {
                builder.set("Amplitude Scaling X", self.amplitude_scaling_x)
            })
            .and_then(|builder| {
                builder.set("Amplitude Scaling Y", self.amplitude_scaling_y)
            })
            .and_then(|builder| {
                builder.set("Amplitude Scaling Z", self.amplitude_scaling_z)
            })
            .and_then(|builder| {
                builder.set("Amplitude Scaling W", self.amplitude_scaling_w)
            })
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(|builder| builder.set("Warp Amplitude", &self.warp_amplitude))
            .and_then(NodeBuilder::build)
            .expect("generated from FastNoise2 metadata")
    }
}

/// The original input position is passed into the first domain warp octave
/// The warped output position from the previous octave is passed into
/// the next octave's input position and so on for each octave
/// The final position is used to generate the source node on the attached domain warp node
#[derive(Clone, Debug)]
pub struct DomainWarpFractalProgressive {
    octaves: i32,
    lacunarity: f32,
    domain_warp_source: Node,
    gain: Hybrid,
    weighted_strength: Hybrid,
}

impl DomainWarpFractalProgressive {
    #[allow(dead_code)]
    pub(crate) fn new(domain_warp_source: Node) -> Self {
        Self {
            octaves: 3,
            lacunarity: 2.0,
            domain_warp_source,
            gain: Hybrid::Value(0.5),
            weighted_strength: Hybrid::Value(0.0),
        }
    }

    /// Number of noise layers combined together
    /// More octaves = more detail but slower generation
    /// Each octave adds finer detail at higher frequencies
    ///
    /// Default: `3`
    pub fn with_octaves(mut self, octaves: i32) -> Self {
        self.octaves = octaves;
        self
    }

    /// How much the frequency increases between octaves
    /// 2.0 = Each octave is twice as detailed as the previous
    /// Higher values create more contrast between large and small features
    ///
    /// Default: `2.0`
    pub fn with_lacunarity(mut self, lacunarity: f32) -> Self {
        self.lacunarity = lacunarity;
        self
    }

    /// Multiplier for how much each octave contributes to the final result
    /// Lower values create smoother, more uniform noise
    /// Higher values preserve more detail from smaller octaves
    ///
    /// Default: `0.5`
    pub fn with_gain(mut self, gain: impl Into<Hybrid>) -> Self {
        self.gain = gain.into();
        self
    }

    /// Scales the contribution of higher octaves based on the output value of previous octaves
    /// Low values from lower octaves reduces contribution from higher octaves
    /// Setting this higher creates smoother output in low areas while retaining octave details in high areas
    ///
    /// Default: `0.0`
    pub fn with_weighted_strength(
        mut self,
        weighted_strength: impl Into<Hybrid>,
    ) -> Self {
        self.weighted_strength = weighted_strength.into();
        self
    }
}

impl Generator for DomainWarpFractalProgressive {
    fn build(&self) -> Node {
        NodeBuilder::new("DomainWarpFractalProgressive")
            .and_then(|builder| builder.set("Octaves", self.octaves))
            .and_then(|builder| builder.set("Lacunarity", self.lacunarity))
            .and_then(|builder| {
                builder.set("Domain Warp Source", &self.domain_warp_source)
            })
            .and_then(|builder| builder.set("Gain", &self.gain))
            .and_then(|builder| {
                builder.set("Weighted Strength", &self.weighted_strength)
            })
            .and_then(NodeBuilder::build)
            .expect("generated from FastNoise2 metadata")
    }
}

/// The original input position is passed into all domain warp octaves
/// The warped offset from all octaves is accumulated
/// and added to the original input position
/// This position is used to generate the source node on the attached domain warp node
#[derive(Clone, Debug)]
pub struct DomainWarpFractalIndependent {
    octaves: i32,
    lacunarity: f32,
    domain_warp_source: Node,
    gain: Hybrid,
    weighted_strength: Hybrid,
}

impl DomainWarpFractalIndependent {
    #[allow(dead_code)]
    pub(crate) fn new(domain_warp_source: Node) -> Self {
        Self {
            octaves: 3,
            lacunarity: 2.0,
            domain_warp_source,
            gain: Hybrid::Value(0.5),
            weighted_strength: Hybrid::Value(0.0),
        }
    }

    /// Number of noise layers combined together
    /// More octaves = more detail but slower generation
    /// Each octave adds finer detail at higher frequencies
    ///
    /// Default: `3`
    pub fn with_octaves(mut self, octaves: i32) -> Self {
        self.octaves = octaves;
        self
    }

    /// How much the frequency increases between octaves
    /// 2.0 = Each octave is twice as detailed as the previous
    /// Higher values create more contrast between large and small features
    ///
    /// Default: `2.0`
    pub fn with_lacunarity(mut self, lacunarity: f32) -> Self {
        self.lacunarity = lacunarity;
        self
    }

    /// Multiplier for how much each octave contributes to the final result
    /// Lower values create smoother, more uniform noise
    /// Higher values preserve more detail from smaller octaves
    ///
    /// Default: `0.5`
    pub fn with_gain(mut self, gain: impl Into<Hybrid>) -> Self {
        self.gain = gain.into();
        self
    }

    /// Scales the contribution of higher octaves based on the output value of previous octaves
    /// Low values from lower octaves reduces contribution from higher octaves
    /// Setting this higher creates smoother output in low areas while retaining octave details in high areas
    ///
    /// Default: `0.0`
    pub fn with_weighted_strength(
        mut self,
        weighted_strength: impl Into<Hybrid>,
    ) -> Self {
        self.weighted_strength = weighted_strength.into();
        self
    }
}

impl Generator for DomainWarpFractalIndependent {
    fn build(&self) -> Node {
        NodeBuilder::new("DomainWarpFractalIndependent")
            .and_then(|builder| builder.set("Octaves", self.octaves))
            .and_then(|builder| builder.set("Lacunarity", self.lacunarity))
            .and_then(|builder| {
                builder.set("Domain Warp Source", &self.domain_warp_source)
            })
            .and_then(|builder| builder.set("Gain", &self.gain))
            .and_then(|builder| {
                builder.set("Weighted Strength", &self.weighted_strength)
            })
            .and_then(NodeBuilder::build)
            .expect("generated from FastNoise2 metadata")
    }
}
