// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.
//! Domain Modifiers nodes.

use super::enums::{RemoveDimensionType, RotationType};
use crate::node::{Generator, Hybrid, Node, NodeBuilder};

/// Scales the input coordinates uniformly before passing them to the source generator.
#[derive(Clone, Debug)]
pub struct DomainScale {
    scaling: f32,
    source: Node,
}

impl DomainScale {
    pub(crate) fn new(source: Node) -> Self {
        Self { scaling: 1.0, source }
    }

    /// Default: `1.0`
    pub fn with_scaling(mut self, scaling: f32) -> Self {
        self.scaling = scaling;
        self
    }
}

impl Generator for DomainScale {
    fn build(&self) -> Node {
        NodeBuilder::new("DomainScale")
            .and_then(|builder| builder.set("Scaling", self.scaling))
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Adds an offset to the input coordinates before passing them to the source generator
/// Doesn't add or remove dimensions
#[derive(Clone, Debug)]
pub struct DomainOffset {
    source: Node,
    offset_x: Hybrid,
    offset_y: Hybrid,
    offset_z: Hybrid,
    offset_w: Hybrid,
}

impl DomainOffset {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            source,
            offset_x: Hybrid::Value(0.0),
            offset_y: Hybrid::Value(0.0),
            offset_z: Hybrid::Value(0.0),
            offset_w: Hybrid::Value(0.0),
        }
    }

    /// Default: `0.0`
    pub fn with_offset_x(mut self, offset_x: impl Into<Hybrid>) -> Self {
        self.offset_x = offset_x.into();
        self
    }

    /// Default: `0.0`
    pub fn with_offset_y(mut self, offset_y: impl Into<Hybrid>) -> Self {
        self.offset_y = offset_y.into();
        self
    }

    /// Default: `0.0`
    pub fn with_offset_z(mut self, offset_z: impl Into<Hybrid>) -> Self {
        self.offset_z = offset_z.into();
        self
    }

    /// Default: `0.0`
    pub fn with_offset_w(mut self, offset_w: impl Into<Hybrid>) -> Self {
        self.offset_w = offset_w.into();
        self
    }
}

impl Generator for DomainOffset {
    fn build(&self) -> Node {
        NodeBuilder::new("DomainOffset")
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(|builder| builder.set("Offset X", &self.offset_x))
            .and_then(|builder| builder.set("Offset Y", &self.offset_y))
            .and_then(|builder| builder.set("Offset Z", &self.offset_z))
            .and_then(|builder| builder.set("Offset W", &self.offset_w))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Rotates the input coordinates around the origin before passing them to the source generator
/// For 2D input coordinates a 2D rotation with Yaw is performed if Pitch and Roll are 0, otherwise a 3D rotation is performed
/// For 3D input coordinates a 3D rotation is performed
/// For 4D input coordinates no rotation is applied
#[derive(Clone, Debug)]
pub struct DomainRotate {
    yaw: f32,
    pitch: f32,
    roll: f32,
    source: Node,
}

impl DomainRotate {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            yaw: 0.0,
            pitch: 0.0,
            roll: 0.0,
            source,
        }
    }

    /// Default: `0.0`
    pub fn with_yaw(mut self, yaw: f32) -> Self {
        self.yaw = yaw;
        self
    }

    /// Default: `0.0`
    pub fn with_pitch(mut self, pitch: f32) -> Self {
        self.pitch = pitch;
        self
    }

    /// Default: `0.0`
    pub fn with_roll(mut self, roll: f32) -> Self {
        self.roll = roll;
        self
    }
}

impl Generator for DomainRotate {
    fn build(&self) -> Node {
        NodeBuilder::new("DomainRotate")
            .and_then(|builder| builder.set("Yaw", self.yaw))
            .and_then(|builder| builder.set("Pitch", self.pitch))
            .and_then(|builder| builder.set("Roll", self.roll))
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Scales each axis of the input coordinates independently before passing them to the source generator.
#[derive(Clone, Debug)]
pub struct DomainAxisScale {
    scaling_x: f32,
    scaling_y: f32,
    scaling_z: f32,
    scaling_w: f32,
    source: Node,
}

impl DomainAxisScale {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            scaling_x: 1.0,
            scaling_y: 1.0,
            scaling_z: 1.0,
            scaling_w: 1.0,
            source,
        }
    }

    /// Default: `1.0`
    pub fn with_scaling_x(mut self, scaling_x: f32) -> Self {
        self.scaling_x = scaling_x;
        self
    }

    /// Default: `1.0`
    pub fn with_scaling_y(mut self, scaling_y: f32) -> Self {
        self.scaling_y = scaling_y;
        self
    }

    /// Default: `1.0`
    pub fn with_scaling_z(mut self, scaling_z: f32) -> Self {
        self.scaling_z = scaling_z;
        self
    }

    /// Default: `1.0`
    pub fn with_scaling_w(mut self, scaling_w: f32) -> Self {
        self.scaling_w = scaling_w;
        self
    }
}

impl Generator for DomainAxisScale {
    fn build(&self) -> Node {
        NodeBuilder::new("DomainAxisScale")
            .and_then(|builder| builder.set("Scaling X", self.scaling_x))
            .and_then(|builder| builder.set("Scaling Y", self.scaling_y))
            .and_then(|builder| builder.set("Scaling Z", self.scaling_z))
            .and_then(|builder| builder.set("Scaling W", self.scaling_w))
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Adds a dimension to the input coordinates, new dimension is always the last dimension
/// The coordinates with the new dimension are passed to the source generator
#[derive(Clone, Debug)]
pub struct AddDimension {
    source: Node,
    new_dimension_position: Hybrid,
}

impl AddDimension {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            source,
            new_dimension_position: Hybrid::Value(0.0),
        }
    }

    /// The position of the new dimension
    ///
    /// Default: `0.0`
    pub fn with_new_dimension_position(
        mut self,
        new_dimension_position: impl Into<Hybrid>,
    ) -> Self {
        self.new_dimension_position = new_dimension_position.into();
        self
    }
}

impl Generator for AddDimension {
    fn build(&self) -> Node {
        NodeBuilder::new("AddDimension")
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(|builder| {
                builder.set("New Dimension Position", &self.new_dimension_position)
            })
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Removes the specified dimension from the input coordinates before passing them to the source generator
#[derive(Clone, Debug)]
pub struct RemoveDimension {
    remove_dimension: RemoveDimensionType,
    source: Node,
}

impl RemoveDimension {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            remove_dimension: RemoveDimensionType::Y,
            source,
        }
    }

    /// Default: `RemoveDimensionType::Y`
    pub fn with_remove_dimension(
        mut self,
        remove_dimension: RemoveDimensionType,
    ) -> Self {
        self.remove_dimension = remove_dimension;
        self
    }
}

impl Generator for RemoveDimension {
    fn build(&self) -> Node {
        NodeBuilder::new("RemoveDimension")
            .and_then(|builder| {
                builder.set("Remove Dimension", self.remove_dimension.name())
            })
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Applies preset rotation to improve noise in specific 3D planes. Faster than DomainRotate.
/// This helps reduce axis aligned artifacts in 3D noise for the specified plane.
/// For 2D input coordinates a 3rd dimension is added and the noise is optimized for the XY plane
/// For 4D input coordinates only the first 3 dimensions are rotated, the 4th dimension is passed through unchanged
#[derive(Clone, Debug)]
pub struct DomainRotatePlane {
    rotation_type: RotationType,
    source: Node,
}

impl DomainRotatePlane {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            rotation_type: RotationType::ImproveXyPlanes,
            source,
        }
    }

    /// Default: `RotationType::ImproveXyPlanes`
    pub fn with_rotation_type(mut self, rotation_type: RotationType) -> Self {
        self.rotation_type = rotation_type;
        self
    }
}

impl Generator for DomainRotatePlane {
    fn build(&self) -> Node {
        NodeBuilder::new("DomainRotatePlane")
            .and_then(|builder| builder.set("Rotation Type", self.rotation_type.name()))
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}
