// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.
//! Enum member types.

/// Used by [`DistanceToPoint`](super::DistanceToPoint), [`CellularValue`](super::CellularValue), [`CellularDistance`](super::CellularDistance), [`CellularLookup`](super::CellularLookup).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum DistanceFunction {
    Euclidean,
    EuclideanSquared,
    Manhattan,
    Hybrid,
    MaxAxis,
    Minkowski,
}

impl DistanceFunction {
    /// The FastNoise2 name of the value.
    pub(crate) fn name(self) -> &'static str {
        match self {
            Self::Euclidean => "Euclidean",
            Self::EuclideanSquared => "Euclidean Squared",
            Self::Manhattan => "Manhattan",
            Self::Hybrid => "Hybrid",
            Self::MaxAxis => "Max Axis",
            Self::Minkowski => "Minkowski",
        }
    }
}

/// Easing function
///
/// Used by [`Fade`](super::Fade).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Interpolation {
    Linear,
    Hermite,
    Quintic,
}

impl Interpolation {
    /// The FastNoise2 name of the value.
    pub(crate) fn name(self) -> &'static str {
        match self {
            Self::Linear => "Linear",
            Self::Hermite => "Hermite",
            Self::Quintic => "Quintic",
        }
    }
}

/// Used by [`RemoveDimension`](super::RemoveDimension).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RemoveDimensionType {
    X,
    Y,
    Z,
    W,
}

impl RemoveDimensionType {
    /// The FastNoise2 name of the value.
    pub(crate) fn name(self) -> &'static str {
        match self {
            Self::X => "X",
            Self::Y => "Y",
            Self::Z => "Z",
            Self::W => "W",
        }
    }
}

/// How to combine Index 0 & Index 1
///
/// Used by [`CellularDistance`](super::CellularDistance).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ReturnType {
    Index0,
    Index0Add1,
    Index0Sub1,
    Index0Mul1,
    Index0Div1,
}

impl ReturnType {
    /// The FastNoise2 name of the value.
    pub(crate) fn name(self) -> &'static str {
        match self {
            Self::Index0 => "Index0",
            Self::Index0Add1 => "Index0Add1",
            Self::Index0Sub1 => "Index0Sub1",
            Self::Index0Mul1 => "Index0Mul1",
            Self::Index0Div1 => "Index0Div1",
        }
    }
}

/// Used by [`DomainRotatePlane`](super::DomainRotatePlane).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RotationType {
    ImproveXyPlanes,
    ImproveXzPlanes,
}

impl RotationType {
    /// The FastNoise2 name of the value.
    pub(crate) fn name(self) -> &'static str {
        match self {
            Self::ImproveXyPlanes => "Improve XY Planes",
            Self::ImproveXzPlanes => "Improve XZ Planes",
        }
    }
}

/// Construction used by the noise to produce a vector output
///
/// Used by [`DomainWarpSimplex`](super::DomainWarpSimplex), [`DomainWarpSuperSimplex`](super::DomainWarpSuperSimplex).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum VectorizationScheme {
    OrthogonalGradientMatrix,
    GradientOuterProduct,
}

impl VectorizationScheme {
    /// The FastNoise2 name of the value.
    pub(crate) fn name(self) -> &'static str {
        match self {
            Self::OrthogonalGradientMatrix => "Orthogonal Gradient Matrix",
            Self::GradientOuterProduct => "Gradient Outer Product",
        }
    }
}
