// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.
//! Chaining methods, creating a node from the generator used as its first input.

use super::*;
use crate::node::Generator;

/// Generators accepted by `Domain Warp Source` inputs.
pub trait DomainWarpSource: Generator {}
impl DomainWarpSource for DomainWarpSimplex {}
impl DomainWarpSource for DomainWarpSuperSimplex {}
impl DomainWarpSource for DomainWarpGradient {}
impl<G: DomainWarpSource + ?Sized> DomainWarpSource for &G {}

/// Chaining methods available on every generator.
pub trait GeneratorExt: Generator {
    /// Creates a [`CellularLookup`] node with this generator as its `Lookup` input.
    fn cellular_lookup(&self) -> CellularLookup {
        CellularLookup::new(self.build())
    }

    /// Creates a [`FractalFBm`] node with this generator as its `Source` input.
    fn fractal_f_bm(&self) -> FractalFBm {
        FractalFBm::new(self.build())
    }

    /// Creates a [`PingPong`] node with this generator as its `Source` input.
    fn ping_pong(&self) -> PingPong {
        PingPong::new(self.build())
    }

    /// Creates a [`FractalRidged`] node with this generator as its `Source` input.
    fn fractal_ridged(&self) -> FractalRidged {
        FractalRidged::new(self.build())
    }

    /// Creates a [`DomainWarpSimplex`] node with this generator as its `Source` input.
    fn domain_warp_simplex(&self) -> DomainWarpSimplex {
        DomainWarpSimplex::new(self.build())
    }

    /// Creates a [`DomainWarpSuperSimplex`] node with this generator as its `Source` input.
    fn domain_warp_super_simplex(&self) -> DomainWarpSuperSimplex {
        DomainWarpSuperSimplex::new(self.build())
    }

    /// Creates a [`DomainWarpGradient`] node with this generator as its `Source` input.
    fn domain_warp_gradient(&self) -> DomainWarpGradient {
        DomainWarpGradient::new(self.build())
    }

    /// Creates a [`Add`] node with this generator as its `LHS` input.
    fn add(&self) -> Add {
        Add::new(self.build())
    }

    /// Creates a [`Multiply`] node with this generator as its `LHS` input.
    fn multiply(&self) -> Multiply {
        Multiply::new(self.build())
    }

    /// Creates a [`Abs`] node with this generator as its `Source` input.
    fn abs(&self) -> Abs {
        Abs::new(self.build())
    }

    /// Creates a [`Min`] node with this generator as its `LHS` input.
    fn min(&self) -> Min {
        Min::new(self.build())
    }

    /// Creates a [`Max`] node with this generator as its `LHS` input.
    fn max(&self) -> Max {
        Max::new(self.build())
    }

    /// Creates a [`MinSmooth`] node with this generator as its `LHS` input.
    fn min_smooth(&self) -> MinSmooth {
        MinSmooth::new(self.build())
    }

    /// Creates a [`MaxSmooth`] node with this generator as its `LHS` input.
    fn max_smooth(&self) -> MaxSmooth {
        MaxSmooth::new(self.build())
    }

    /// Creates a [`SignedSquareRoot`] node with this generator as its `Source` input.
    fn signed_square_root(&self) -> SignedSquareRoot {
        SignedSquareRoot::new(self.build())
    }

    /// Creates a [`PowInt`] node with this generator as its `Value` input.
    fn pow_int(&self) -> PowInt {
        PowInt::new(self.build())
    }

    /// Creates a [`DomainScale`] node with this generator as its `Source` input.
    fn domain_scale(&self) -> DomainScale {
        DomainScale::new(self.build())
    }

    /// Creates a [`DomainOffset`] node with this generator as its `Source` input.
    fn domain_offset(&self) -> DomainOffset {
        DomainOffset::new(self.build())
    }

    /// Creates a [`DomainRotate`] node with this generator as its `Source` input.
    fn domain_rotate(&self) -> DomainRotate {
        DomainRotate::new(self.build())
    }

    /// Creates a [`DomainAxisScale`] node with this generator as its `Source` input.
    fn domain_axis_scale(&self) -> DomainAxisScale {
        DomainAxisScale::new(self.build())
    }

    /// Creates a [`SeedOffset`] node with this generator as its `Source` input.
    fn seed_offset(&self) -> SeedOffset {
        SeedOffset::new(self.build())
    }

    /// Creates a [`ConvertRGBA8`] node with this generator as its `Source` input.
    fn convert_rgba8(&self) -> ConvertRGBA8 {
        ConvertRGBA8::new(self.build())
    }

    /// Creates a [`GeneratorCache`] node with this generator as its `Source` input.
    fn generator_cache(&self) -> GeneratorCache {
        GeneratorCache::new(self.build())
    }

    /// Creates a [`Fade`] node with this generator as its `A` input.
    fn fade(&self, b: impl Generator) -> Fade {
        Fade::new(self.build(), b.build())
    }

    /// Creates a [`Remap`] node with this generator as its `Source` input.
    fn remap(&self) -> Remap {
        Remap::new(self.build())
    }

    /// Creates a [`Terrace`] node with this generator as its `Source` input.
    fn terrace(&self) -> Terrace {
        Terrace::new(self.build())
    }

    /// Creates a [`AddDimension`] node with this generator as its `Source` input.
    fn add_dimension(&self) -> AddDimension {
        AddDimension::new(self.build())
    }

    /// Creates a [`RemoveDimension`] node with this generator as its `Source` input.
    fn remove_dimension(&self) -> RemoveDimension {
        RemoveDimension::new(self.build())
    }

    /// Creates a [`DomainRotatePlane`] node with this generator as its `Source` input.
    fn domain_rotate_plane(&self) -> DomainRotatePlane {
        DomainRotatePlane::new(self.build())
    }
}

impl<G: Generator + ?Sized> GeneratorExt for G {}

/// Chaining methods available on [`DomainWarpSource`] generators.
pub trait DomainWarpSourceExt: DomainWarpSource {
    /// Creates a [`DomainWarpFractalProgressive`] node with this generator as its `Domain Warp Source` input.
    fn domain_warp_fractal_progressive(&self) -> DomainWarpFractalProgressive {
        DomainWarpFractalProgressive::new(self.build())
    }

    /// Creates a [`DomainWarpFractalIndependent`] node with this generator as its `Domain Warp Source` input.
    fn domain_warp_fractal_independent(&self) -> DomainWarpFractalIndependent {
        DomainWarpFractalIndependent::new(self.build())
    }
}

impl<G: DomainWarpSource + ?Sized> DomainWarpSourceExt for G {}
