// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.
//! Fractal nodes.

use crate::node::{Generator, Hybrid, Node, NodeBuilder};

/// Fractional Brownian Motion - Builds up realistic natural textures
/// Combines multiple octaves where each adds progressively finer detail
/// Creates smooth, flowing patterns ideal for terrain, clouds, and organic textures
/// Each octave's contribution decreases by the Gain amount
#[derive(Clone, Debug)]
pub struct FractalFBm {
    octaves: i32,
    lacunarity: f32,
    source: Node,
    gain: Hybrid,
    weighted_strength: Hybrid,
}

impl FractalFBm {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            octaves: 3,
            lacunarity: 2.0,
            source,
            gain: Hybrid::Value(0.5),
            weighted_strength: Hybrid::Value(0.0),
        }
    }

    /// Number of noise layers combined together
    /// More octaves = more detail but slower generation
    /// Each octave adds finer detail at higher frequencies
    ///
    /// Default: `3`
    pub fn with_octaves(mut self, octaves: i32) -> Self {
        self.octaves = octaves;
        self
    }

    /// How much the frequency increases between octaves
    /// 2.0 = Each octave is twice as detailed as the previous
    /// Higher values create more contrast between large and small features
    ///
    /// Default: `2.0`
    pub fn with_lacunarity(mut self, lacunarity: f32) -> Self {
        self.lacunarity = lacunarity;
        self
    }

    /// Multiplier for how much each octave contributes to the final result
    /// Lower values create smoother, more uniform noise
    /// Higher values preserve more detail from smaller octaves
    ///
    /// Default: `0.5`
    pub fn with_gain(mut self, gain: impl Into<Hybrid>) -> Self {
        self.gain = gain.into();
        self
    }

    /// Scales the contribution of higher octaves based on the output value of previous octaves
    /// Low values from lower octaves reduces contribution from higher octaves
    /// Setting this higher creates smoother output in low areas while retaining octave details in high areas
    ///
    /// Default: `0.0`
    pub fn with_weighted_strength(
        mut self,
        weighted_strength: impl Into<Hybrid>,
    ) -> Self {
        self.weighted_strength = weighted_strength.into();
        self
    }
}

impl Generator for FractalFBm {
    fn build(&self) -> Node {
        NodeBuilder::new("FractalFBm")
            .and_then(|builder| builder.set("Octaves", self.octaves))
            .and_then(|builder| builder.set("Lacunarity", self.lacunarity))
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(|builder| builder.set("Gain", &self.gain))
            .and_then(|builder| {
                builder.set("Weighted Strength", &self.weighted_strength)
            })
            .and_then(NodeBuilder::build)
            .expect("generated from FastNoise2 metadata")
    }
}

/// Creates sharp ridges and valleys by inverting and combining noise octaves
/// Produces dramatic mountain-like terrain with defined peaks and canyons
/// Higher octaves sharpen the ridges rather than adding smooth detail
/// Perfect for creating realistic mountain ranges and rocky formations
#[derive(Clone, Debug)]
pub struct FractalRidged {
    octaves: i32,
    lacunarity: f32,
    source: Node,
    gain: Hybrid,
    weighted_strength: Hybrid,
}

impl FractalRidged {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            octaves: 3,
            lacunarity: 2.0,
            source,
            gain: Hybrid::Value(0.5),
            weighted_strength: Hybrid::Value(0.0),
        }
    }

    /// Number of noise layers combined together
    /// More octaves = more detail but slower generation
    /// Each octave adds finer detail at higher frequencies
    ///
    /// Default: `3`
    pub fn with_octaves(mut self, octaves: i32) -> Self {
        self.octaves = octaves;
        self
    }

    /// How much the frequency increases between octaves
    /// 2.0 = Each octave is twice as detailed as the previous
    /// Higher values create more contrast between large and small features
    ///
    /// Default: `2.0`
    pub fn with_lacunarity(mut self, lacunarity: f32) -> Self {
        self.lacunarity = lacunarity;
        self
    }

    /// Multiplier for how much each octave contributes to the final result
    /// Lower values create smoother, more uniform noise
    /// Higher values preserve more detail from smaller octaves
    ///
    /// Default: `0.5`
    pub fn with_gain(mut self, gain: impl Into<Hybrid>) -> Self {
        self.gain = gain.into();
        self
    }

    /// Scales the contribution of higher octaves based on the output value of previous octaves
    /// Low values from lower octaves reduces contribution from higher octaves
    /// Setting this higher creates smoother output in low areas while retaining octave details in high areas
    ///
    /// Default: `0.0`
    pub fn with_weighted_strength(
        mut self,
        weighted_strength: impl Into<Hybrid>,
    ) -> Self {
        self.weighted_strength = weighted_strength.into();
        self
    }
}

impl Generator for FractalRidged {
    fn build(&self) -> Node {
        NodeBuilder::new("FractalRidged")
            .and_then(|builder| builder.set("Octaves", self.octaves))
            .and_then(|builder| builder.set("Lacunarity", self.lacunarity))
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(|builder| builder.set("Gain", &self.gain))
            .and_then(|builder| {
                builder.set("Weighted Strength", &self.weighted_strength)
            })
            .and_then(NodeBuilder::build)
            .expect("generated from FastNoise2 metadata")
    }
}
