// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.
//! Modifiers nodes.

use crate::node::{Generator, Hybrid, Node, NodeBuilder};

/// Creates flow patterns by 'ping-ponging' input values between extremes
/// Multiplies input values by the ping pong strength and reflects values
/// that would normally go beyond -1.0 or 1.0 and bounce back instead.
/// Produces smooth, flowing patterns similar to contour lines
#[derive(Clone, Debug)]
pub struct PingPong {
    source: Node,
    ping_pong_strength: Hybrid,
}

impl PingPong {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            source,
            ping_pong_strength: Hybrid::Value(2.0),
        }
    }

    /// Controls how dramatically values bounce between extremes
    /// Higher values create more pronounced ping-pong effects
    ///
    /// Default: `2.0`
    pub fn with_ping_pong_strength(
        mut self,
        ping_pong_strength: impl Into<Hybrid>,
    ) -> Self {
        self.ping_pong_strength = ping_pong_strength.into();
        self
    }
}

impl Generator for PingPong {
    fn build(&self) -> Node {
        NodeBuilder::new("PingPong")
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(|builder| {
                builder.set("Ping Pong Strength", &self.ping_pong_strength)
            })
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Returns the absolute value of the source output.
#[derive(Clone, Debug)]
pub struct Abs {
    source: Node,
}

impl Abs {
    pub(crate) fn new(source: Node) -> Self {
        Self { source }
    }
}

impl Generator for Abs {
    fn build(&self) -> Node {
        NodeBuilder::new("Abs")
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Returns the square root of the absolute value of the source output,
/// preserving the original sign (signed square root).
#[derive(Clone, Debug)]
pub struct SignedSquareRoot {
    source: Node,
}

impl SignedSquareRoot {
    pub(crate) fn new(source: Node) -> Self {
        Self { source }
    }
}

impl Generator for SignedSquareRoot {
    fn build(&self) -> Node {
        NodeBuilder::new("SignedSquareRoot")
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Offsets the input seed before passing it to the source generator.
#[derive(Clone, Debug)]
pub struct SeedOffset {
    seed_offset: i32,
    source: Node,
}

impl SeedOffset {
    pub(crate) fn new(source: Node) -> Self {
        Self { seed_offset: 1, source }
    }

    /// Default: `1`
    pub fn with_seed_offset(mut self, seed_offset: i32) -> Self {
        self.seed_offset = seed_offset;
        self
    }
}

impl Generator for SeedOffset {
    fn build(&self) -> Node {
        NodeBuilder::new("SeedOffset")
            .and_then(|builder| builder.set("Seed Offset", self.seed_offset))
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Used for converting a float into a greyscale RGBA8 texture format output
/// Clamps the source output between Min/Max, scales it to 0-255, and packs the result
/// into an RGBA8 color stored in a float. RGB will be the same value, Alpha is always 255
#[derive(Clone, Debug)]
pub struct ConvertRGBA8 {
    min: f32,
    max: f32,
    source: Node,
}

impl ConvertRGBA8 {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            min: -1.0,
            max: 1.0,
            source,
        }
    }

    /// Default: `-1.0`
    pub fn with_min(mut self, min: f32) -> Self {
        self.min = min;
        self
    }

    /// Default: `1.0`
    pub fn with_max(mut self, max: f32) -> Self {
        self.max = max;
        self
    }
}

impl Generator for ConvertRGBA8 {
    fn build(&self) -> Node {
        NodeBuilder::new("ConvertRGBA8")
            .and_then(|builder| builder.set("Min", self.min))
            .and_then(|builder| builder.set("Max", self.max))
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Caches the output of the source generator. If the same input coordinates and seed are
/// requested again, the cached value is returned, improving performance for complex source generators
#[derive(Clone, Debug)]
pub struct GeneratorCache {
    source: Node,
}

impl GeneratorCache {
    pub(crate) fn new(source: Node) -> Self {
        Self { source }
    }
}

impl Generator for GeneratorCache {
    fn build(&self) -> Node {
        NodeBuilder::new("GeneratorCache")
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Remaps the output value of the source generator from one range to another
/// Optionally clamps output to the To Min/Max range
#[derive(Clone, Debug)]
pub struct Remap {
    clamp_output: bool,
    source: Node,
    from_min: Hybrid,
    from_max: Hybrid,
    to_min: Hybrid,
    to_max: Hybrid,
}

impl Remap {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            clamp_output: false,
            source,
            from_min: Hybrid::Value(-1.0),
            from_max: Hybrid::Value(1.0),
            to_min: Hybrid::Value(0.0),
            to_max: Hybrid::Value(1.0),
        }
    }

    /// Clamp output between "To Min" & "To Max"
    ///
    /// Default: `false`
    pub fn with_clamp_output(mut self, clamp_output: bool) -> Self {
        self.clamp_output = clamp_output;
        self
    }

    /// Default: `-1.0`
    pub fn with_from_min(mut self, from_min: impl Into<Hybrid>) -> Self {
        self.from_min = from_min.into();
        self
    }

    /// Default: `1.0`
    pub fn with_from_max(mut self, from_max: impl Into<Hybrid>) -> Self {
        self.from_max = from_max.into();
        self
    }

    /// Default: `0.0`
    pub fn with_to_min(mut self, to_min: impl Into<Hybrid>) -> Self {
        self.to_min = to_min.into();
        self
    }

    /// Default: `1.0`
    pub fn with_to_max(mut self, to_max: impl Into<Hybrid>) -> Self {
        self.to_max = to_max.into();
        self
    }
}

impl Generator for Remap {
    fn build(&self) -> Node {
        NodeBuilder::new("Remap")
            .and_then(|builder| {
                builder
                    .set(
                        "Clamp Output",
                        if self.clamp_output { "True" } else { "False" },
                    )
            })
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(|builder| builder.set("From Min", &self.from_min))
            .and_then(|builder| builder.set("From Max", &self.from_max))
            .and_then(|builder| builder.set("To Min", &self.to_min))
            .and_then(|builder| builder.set("To Max", &self.to_max))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Cuts the input value into steps to give a terraced terrain effect
#[derive(Clone, Debug)]
pub struct Terrace {
    step_count: f32,
    source: Node,
    smoothness: Hybrid,
}

impl Terrace {
    pub(crate) fn new(source: Node) -> Self {
        Self {
            step_count: 1.0,
            source,
            smoothness: Hybrid::Value(0.0),
        }
    }

    /// Increasing the step count reduces the size of each step
    ///
    /// Default: `1.0`
    pub fn with_step_count(mut self, step_count: f32) -> Self {
        self.step_count = step_count;
        self
    }

    /// How smooth the transitions between steps are
    ///
    /// Default: `0.0`
    pub fn with_smoothness(mut self, smoothness: impl Into<Hybrid>) -> Self {
        self.smoothness = smoothness.into();
        self
    }
}

impl Generator for Terrace {
    fn build(&self) -> Node {
        NodeBuilder::new("Terrace")
            .and_then(|builder| builder.set("Step Count", self.step_count))
            .and_then(|builder| builder.set("Source", &self.source))
            .and_then(|builder| builder.set("Smoothness", &self.smoothness))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}
