// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.
//! Operators nodes.

use crate::node::{Generator, Hybrid, Node, NodeBuilder};

/// Add node.
#[derive(Clone, Debug)]
pub struct Add {
    lhs: Node,
    rhs: Hybrid,
}

impl Add {
    pub(crate) fn new(lhs: Node) -> Self {
        Self {
            lhs,
            rhs: Hybrid::Value(0.0),
        }
    }

    /// Default: `0.0`
    pub fn with_rhs(mut self, rhs: impl Into<Hybrid>) -> Self {
        self.rhs = rhs.into();
        self
    }
}

impl Generator for Add {
    fn build(&self) -> Node {
        NodeBuilder::new("Add")
            .and_then(|builder| builder.set("LHS", &self.lhs))
            .and_then(|builder| builder.set("RHS", &self.rhs))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Subtract node.
#[derive(Clone, Debug)]
pub struct Subtract {
    lhs: Hybrid,
    rhs: Hybrid,
}

impl Default for Subtract {
    fn default() -> Self {
        Self {
            lhs: Hybrid::Value(0.0),
            rhs: Hybrid::Value(0.0),
        }
    }
}

/// Creates a [`Subtract`] node with its default values.
pub fn subtract() -> Subtract {
    Subtract::default()
}

impl Subtract {
    /// Default: `0.0`
    pub fn with_lhs(mut self, lhs: impl Into<Hybrid>) -> Self {
        self.lhs = lhs.into();
        self
    }

    /// Default: `0.0`
    pub fn with_rhs(mut self, rhs: impl Into<Hybrid>) -> Self {
        self.rhs = rhs.into();
        self
    }
}

impl Generator for Subtract {
    fn build(&self) -> Node {
        NodeBuilder::new("Subtract")
            .and_then(|builder| builder.set("LHS", &self.lhs))
            .and_then(|builder| builder.set("RHS", &self.rhs))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Multiply node.
#[derive(Clone, Debug)]
pub struct Multiply {
    lhs: Node,
    rhs: Hybrid,
}

impl Multiply {
    pub(crate) fn new(lhs: Node) -> Self {
        Self {
            lhs,
            rhs: Hybrid::Value(0.0),
        }
    }

    /// Default: `0.0`
    pub fn with_rhs(mut self, rhs: impl Into<Hybrid>) -> Self {
        self.rhs = rhs.into();
        self
    }
}

impl Generator for Multiply {
    fn build(&self) -> Node {
        NodeBuilder::new("Multiply")
            .and_then(|builder| builder.set("LHS", &self.lhs))
            .and_then(|builder| builder.set("RHS", &self.rhs))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Divide node.
#[derive(Clone, Debug)]
pub struct Divide {
    lhs: Hybrid,
    rhs: Hybrid,
}

impl Default for Divide {
    fn default() -> Self {
        Self {
            lhs: Hybrid::Value(0.0),
            rhs: Hybrid::Value(0.0),
        }
    }
}

/// Creates a [`Divide`] node with its default values.
pub fn divide() -> Divide {
    Divide::default()
}

impl Divide {
    /// Default: `0.0`
    pub fn with_lhs(mut self, lhs: impl Into<Hybrid>) -> Self {
        self.lhs = lhs.into();
        self
    }

    /// Default: `0.0`
    pub fn with_rhs(mut self, rhs: impl Into<Hybrid>) -> Self {
        self.rhs = rhs.into();
        self
    }
}

impl Generator for Divide {
    fn build(&self) -> Node {
        NodeBuilder::new("Divide")
            .and_then(|builder| builder.set("LHS", &self.lhs))
            .and_then(|builder| builder.set("RHS", &self.rhs))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}

/// Modulus node.
#[derive(Clone, Debug)]
pub struct Modulus {
    lhs: Hybrid,
    rhs: Hybrid,
}

impl Default for Modulus {
    fn default() -> Self {
        Self {
            lhs: Hybrid::Value(0.0),
            rhs: Hybrid::Value(0.0),
        }
    }
}

/// Creates a [`Modulus`] node with its default values.
pub fn modulus() -> Modulus {
    Modulus::default()
}

impl Modulus {
    /// Default: `0.0`
    pub fn with_lhs(mut self, lhs: impl Into<Hybrid>) -> Self {
        self.lhs = lhs.into();
        self
    }

    /// Default: `0.0`
    pub fn with_rhs(mut self, rhs: impl Into<Hybrid>) -> Self {
        self.rhs = rhs.into();
        self
    }
}

impl Generator for Modulus {
    fn build(&self) -> Node {
        NodeBuilder::new("Modulus")
            .and_then(|builder| builder.set("LHS", &self.lhs))
            .and_then(|builder| builder.set("RHS", &self.rhs))
            .and_then(NodeBuilder::build)
            .unwrap_or_else(|error| panic!("{error}"))
    }
}
