// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.
//! Arithmetic operators on generators, with constants on either side.

use std::ops;
use super::*;
use crate::node::{Generator, Hybrid, Node};

macro_rules! operators {
    ($($generator:ty),*) => {$(
        impl<R: Into<Hybrid>> ops::Add<R> for $generator {
            type Output = Add;

            fn add(self, rhs: R) -> Add {
                Add::new(self.build()).with_rhs(rhs)
            }
        }

        impl<R: Into<Hybrid>> ops::Add<R> for &$generator {
            type Output = Add;

            fn add(self, rhs: R) -> Add {
                Add::new(self.build()).with_rhs(rhs)
            }
        }

        impl ops::Add<$generator> for f32 {
            type Output = Add;

            fn add(self, rhs: $generator) -> Add {
                Add::new(rhs.build()).with_rhs(self)
            }
        }

        impl ops::Add<&$generator> for f32 {
            type Output = Add;

            fn add(self, rhs: &$generator) -> Add {
                Add::new(rhs.build()).with_rhs(self)
            }
        }

        impl<R: Into<Hybrid>> ops::Sub<R> for $generator {
            type Output = Subtract;

            fn sub(self, rhs: R) -> Subtract {
                subtract().with_lhs(self).with_rhs(rhs)
            }
        }

        impl<R: Into<Hybrid>> ops::Sub<R> for &$generator {
            type Output = Subtract;

            fn sub(self, rhs: R) -> Subtract {
                subtract().with_lhs(self).with_rhs(rhs)
            }
        }

        impl ops::Sub<$generator> for f32 {
            type Output = Subtract;

            fn sub(self, rhs: $generator) -> Subtract {
                subtract().with_lhs(self).with_rhs(rhs)
            }
        }

        impl ops::Sub<&$generator> for f32 {
            type Output = Subtract;

            fn sub(self, rhs: &$generator) -> Subtract {
                subtract().with_lhs(self).with_rhs(rhs)
            }
        }

        impl<R: Into<Hybrid>> ops::Mul<R> for $generator {
            type Output = Multiply;

            fn mul(self, rhs: R) -> Multiply {
                Multiply::new(self.build()).with_rhs(rhs)
            }
        }

        impl<R: Into<Hybrid>> ops::Mul<R> for &$generator {
            type Output = Multiply;

            fn mul(self, rhs: R) -> Multiply {
                Multiply::new(self.build()).with_rhs(rhs)
            }
        }

        impl ops::Mul<$generator> for f32 {
            type Output = Multiply;

            fn mul(self, rhs: $generator) -> Multiply {
                Multiply::new(rhs.build()).with_rhs(self)
            }
        }

        impl ops::Mul<&$generator> for f32 {
            type Output = Multiply;

            fn mul(self, rhs: &$generator) -> Multiply {
                Multiply::new(rhs.build()).with_rhs(self)
            }
        }

        impl<R: Into<Hybrid>> ops::Div<R> for $generator {
            type Output = Divide;

            fn div(self, rhs: R) -> Divide {
                divide().with_lhs(self).with_rhs(rhs)
            }
        }

        impl<R: Into<Hybrid>> ops::Div<R> for &$generator {
            type Output = Divide;

            fn div(self, rhs: R) -> Divide {
                divide().with_lhs(self).with_rhs(rhs)
            }
        }

        impl ops::Div<$generator> for f32 {
            type Output = Divide;

            fn div(self, rhs: $generator) -> Divide {
                divide().with_lhs(self).with_rhs(rhs)
            }
        }

        impl ops::Div<&$generator> for f32 {
            type Output = Divide;

            fn div(self, rhs: &$generator) -> Divide {
                divide().with_lhs(self).with_rhs(rhs)
            }
        }

        impl<R: Into<Hybrid>> ops::Rem<R> for $generator {
            type Output = Modulus;

            fn rem(self, rhs: R) -> Modulus {
                modulus().with_lhs(self).with_rhs(rhs)
            }
        }

        impl<R: Into<Hybrid>> ops::Rem<R> for &$generator {
            type Output = Modulus;

            fn rem(self, rhs: R) -> Modulus {
                modulus().with_lhs(self).with_rhs(rhs)
            }
        }

        impl ops::Rem<$generator> for f32 {
            type Output = Modulus;

            fn rem(self, rhs: $generator) -> Modulus {
                modulus().with_lhs(self).with_rhs(rhs)
            }
        }

        impl ops::Rem<&$generator> for f32 {
            type Output = Modulus;

            fn rem(self, rhs: &$generator) -> Modulus {
                modulus().with_lhs(self).with_rhs(rhs)
            }
        }

        /// Negation, multiplying by -1.
        impl ops::Neg for $generator {
            type Output = Multiply;

            fn neg(self) -> Multiply {
                self * -1.0
            }
        }

        /// Negation, multiplying by -1.
        impl ops::Neg for &$generator {
            type Output = Multiply;

            fn neg(self) -> Multiply {
                self * -1.0
            }
        }
    )*};
}

operators!(
    Node, Constant, White, Checkerboard, SineWave, Gradient, DistanceToPoint, Simplex,
    SuperSimplex, Perlin, Value, CellularValue, CellularDistance, CellularLookup,
    FractalFBm, PingPong, FractalRidged, DomainWarpSimplex, DomainWarpSuperSimplex,
    DomainWarpGradient, DomainWarpFractalProgressive, DomainWarpFractalIndependent, Add,
    Subtract, Multiply, Divide, Abs, Min, Max, MinSmooth, MaxSmooth, SignedSquareRoot,
    PowFloat, PowInt, DomainScale, DomainOffset, DomainRotate, DomainAxisScale,
    SeedOffset, ConvertRGBA8, GeneratorCache, Fade, Remap, Terrace, AddDimension,
    RemoveDimension, Modulus, DomainRotatePlane
);
