//! Formatting of generated code.
use proc_macro2::TokenStream;

pub(super) const HEADER: &str =
    "// Generated by fastnoise2-codegen from FastNoise2 metadata, do not edit.\n";

/// Formats generated tokens as a Rust source file.
pub(super) fn render(tokens: TokenStream) -> String {
    format!("{HEADER}{}", render_items(tokens))
}

/// Formats generated items, with blank lines between them.
pub(super) fn render_items(tokens: TokenStream) -> String {
    let file = syn::parse2(tokens).expect("generated code is valid Rust");
    space_items(&prettyplease::unparse(&file))
}

/// Adds a blank line between items, which `prettyplease` puts on consecutive lines.
fn space_items(code: &str) -> String {
    let mut out = String::new();
    let mut previous = "";

    for line in code.lines() {
        let current = line.trim_start();
        let ends_item = previous == "}" || previous.ends_with(';') || previous.ends_with("{}");
        let starts_item = ["///", "#[", "pub ", "pub(", "fn ", "impl ", "impl<", "use "]
            .iter()
            .any(|start| current.starts_with(start));
        let is_use_group = previous.starts_with("use ") && current.starts_with("use ");
        let is_impl_group = previous.ends_with("{}") && current.ends_with("{}");
        let after_module_doc = previous.starts_with("//!") && !current.starts_with("//!");

        if (ends_item && starts_item && !is_use_group && !is_impl_group) || after_module_doc {
            out.push('\n');
        }
        out.push_str(line);
        out.push('\n');
        previous = current;
    }

    out
}
